export class Sound{
 ctx:AudioContext|null=null;master:GainNode|null=null;enabled=true;ambient:AudioBufferSourceNode|null=null;engine:OscillatorNode|null=null;engineGain:GainNode|null=null;
 start(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=.17;this.master.connect(this.ctx.destination);const b=this.ctx.createBuffer(1,this.ctx.sampleRate*3,this.ctx.sampleRate);const d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.13;const n=this.ctx.createBufferSource();n.buffer=b;n.loop=true;const f=this.ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=180;n.connect(f);f.connect(this.master);n.start();this.ambient=n;this.engine=this.ctx.createOscillator();this.engine.type='triangle';this.engineGain=this.ctx.createGain();this.engineGain.gain.value=0;this.engine.connect(this.engineGain);this.engineGain.connect(this.master);this.engine.start()}void this.ctx.resume();this.set(this.enabled)}
 set(on:boolean){this.enabled=on;if(this.master&&this.ctx)this.master.gain.setTargetAtTime(on?.17:0,this.ctx.currentTime,.1)}
 tone(freq=400,duration=.12,volume=.25,delay=0,type:OscillatorType='sine'){if(!this.ctx||!this.master||!this.enabled)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+delay+duration);o.connect(g);g.connect(this.master);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+duration)}
 noise(duration=.1,volume=.25,frequency=900){if(!this.ctx||!this.master||!this.enabled)return;const c=this.ctx,b=c.createBuffer(1,Math.ceil(c.sampleRate*duration),c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=b;f.type='lowpass';f.frequency.value=frequency;g.gain.value=volume;n.connect(f);f.connect(g);g.connect(this.master);n.start()}
 play(kind:string){if(kind==='level'||kind==='success'){[330,440,550,660].forEach((f,i)=>this.tone(f,.3,.24,i*.09,'triangle'))}else if(kind==='gun'){this.noise(.12,.75,1700);this.tone(115,.17,.65,0,'square')}else if(kind==='shotgun'){this.noise(.22,.95,1100);this.tone(62,.28,.8,0,'sawtooth')}else if(kind==='swing'){this.noise(.1,.22,1200);this.tone(150,.08,.14,0,'sawtooth')}else if(kind==='weapon'){this.noise(.13,.42,650);this.tone(82,.16,.55,0,'triangle')}else if(kind==='block'){this.noise(.07,.3,1500);this.tone(310,.1,.22,0,'square')}else if(kind==='dodge')this.noise(.12,.13,1800);else if(kind==='horn'){this.tone(235,.22,.14,0,'square');this.tone(190,.22,.1,.03,'square')}else if(kind==='hit'){this.noise(.08,.3,500);this.tone(75,.15,.55,0,'triangle')}else if(kind==='step')this.tone(100+Math.random()*50,.045,.1,0,'triangle');else if(kind==='danger'){this.tone(170,.35,.4);this.tone(130,.35,.3,.15)}else this.tone(460,.09,.15)}
 vehicle(speed:number,car:boolean){if(this.engine&&this.ctx&&this.engineGain){this.engine.frequency.setTargetAtTime(35+Math.abs(speed)*5,this.ctx.currentTime,.1);this.engineGain.gain.setTargetAtTime(car?.2:0,this.ctx.currentTime,.15)}}
 dispose(){void this.ctx?.close()}
}
