import {test} from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import * as T from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {readFileSync} from 'node:fs';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {fresh,addItem,removeItem,award,saveGame,loadSave,validSave} from '../game/simulation/state';
import {Session} from '../game/simulation/session';
import {xpFor,levelFor,PLACES,streetRank} from '../game/simulation/data';
import {createWorld} from '../game/render/world';
import {Game} from '../game/render/runtime';
import {DEFAULT_PROFILE} from '../game/simulation/profile';
import {pvpZoneAt} from '../game/simulation/online';
const quiet=()=>{const s=new Session();s.notify=()=>{};s.save=async()=>{};return s};
test('XP thresholds are monotonic and support level 99 and multi-level rewards',()=>{for(let l=2;l<=99;l++){assert.ok(xpFor(l)>xpFor(l-1));assert.equal(levelFor(xpFor(l)),l)}const s=fresh();const r=award(s,'Boosting',xpFor(10));assert.equal(r.before,1);assert.equal(r.after,10);assert.ok(r.unlock)});
test('Backpack enforces slot limits, stacking, and atomic purchase failure',()=>{const s=quiet();s.s.cash=1000;for(let i=0;i<22;i++)assert.equal(addItem(s.s,'watch'),true);assert.equal(s.s.inventory.length,24);s.buy('meal');assert.equal(s.s.cash,1000);assert.equal(addItem(s.s,'meal'),false);removeItem(s.s,'watch');s.buy('water');s.buy('water');assert.equal(s.s.inventory.length,24);assert.equal(s.s.inventory.find(i=>i.id==='water')?.qty,2);assert.equal(s.s.cash,992)});
test('Delivery reward is exactly once and requires the destination',()=>{const s=quiet();s.startJob('first');assert.equal(s.s.active,'first');assert.equal(s.finishJob('pawn'),false);assert.equal(s.finishJob('laundry'),true);assert.equal(s.s.cash,75);assert.equal(s.s.xp.Hustling,65);assert.equal(s.s.active,null);assert.equal(s.finishJob('laundry'),false);assert.equal(s.s.cash,75);assert.ok(!s.s.inventory.some(i=>i.id==='parcel'))});
test('Locked jobs and full bags do not create partial delivery state',()=>{const s=quiet();s.startJob('longrun');assert.equal(s.s.active,null);for(let i=0;i<22;i++)addItem(s.s,'watch');s.startJob('first');assert.equal(s.s.active,null)});
test('Bank remains safe on arrest and no transaction can overspend',()=>{const s=quiet();s.bank(1000);assert.equal(s.s.cash,0);assert.equal(s.s.bank,40);s.buy('meal');assert.equal(s.s.inventory.length,2);s.defeat(true);assert.equal(s.s.bank,40);s.bank(-1000);assert.equal(s.s.cash,40);assert.equal(s.s.bank,0)});
test('Save round-trip retains progression and recovers previous valid save',async()=>{const s=fresh();s.cash=123;s.xp.Boosting=130;addItem(s,'water',3);s.owned.push('bike1');s.vehicles.bike1={x:8,z:49,yaw:1,condition:87};await saveGame(s);const restored=await loadSave();assert.deepEqual(restored,s);s.cash=234;await saveGame(s);const db=await new Promise<IDBDatabase>(resolve=>{const r=indexedDB.open('hoodscape-saint-mercer',1);r.onsuccess=()=>resolve(r.result)});await new Promise<void>(resolve=>{const tx=db.transaction('saves','readwrite');tx.objectStore('saves').put({bad:true},'current');tx.oncomplete=()=>resolve()});assert.equal((await loadSave())?.cash,123);db.close()});
test('Invalid imports reject corrupt values, missing parcel, and invalid vehicle IDs',()=>{assert.ok(validSave(fresh()));assert.ok(!validSave({...fresh(),cash:-1}));assert.ok(!validSave({...fresh(),settings:{}}));assert.ok(!validSave({...fresh(),active:'first'}));assert.ok(!validSave({...fresh(),owned:['fake']}));assert.ok(!validSave({...fresh(),heat:99}))});
test('Character origin is permanent, validates, and grants its opening exactly once',()=>{const h=quiet();const profile={...DEFAULT_PROFILE,name:'Nova',background:'mechanic' as const};assert.equal(h.createProfile(profile),true);assert.equal(h.s.xp.Boosting,55);assert.equal(h.s.inventory.filter(i=>i.id==='tool').length,1);assert.equal(h.s.completed['origin:claimed'],1);assert.equal(h.createProfile({...profile,name:'Second'}),false);assert.equal(h.s.xp.Boosting,55);assert.ok(validSave(h.s));assert.ok(!validSave({...h.s,profile:{...profile,name:'X'}}))});
test('Online zones, sandbox routing, and expanded origins remain valid save state',()=>{assert.equal(pvpZoneAt(50,30)?.id,'freight');assert.equal(pvpZoneAt(-45,0)?.id,'south');assert.equal(pvpZoneAt(0,0),null);const h=quiet();assert.ok(h.createProfile({...DEFAULT_PROFILE,name:'Maya',background:'racer'}));assert.equal(h.s.xp.Boosting,80);h.s.path='sandbox';h.s.tutorial={step:8,complete:true};assert.ok(validSave(h.s));assert.ok(!validSave({...h.s,path:'linear'}));assert.ok(!validSave({...h.s,tutorial:{step:99,complete:false}}))});
test('Character preview options persist and legacy profiles receive visual defaults',()=>{const h=quiet();assert.ok(h.createProfile({...DEFAULT_PROFILE,name:'Zion',face:'scarred',head:'locs',body:'broad'}));assert.equal(h.s.profile?.face,'scarred');assert.equal(h.s.profile?.head,'locs');assert.equal(h.s.profile?.body,'broad');const legacy={...fresh(),profile:{...DEFAULT_PROFILE,face:undefined,head:undefined,body:undefined}};assert.ok(validSave(legacy));const migrated=migrateSave(legacy);assert.equal(migrated.profile?.face,'classic');assert.equal(migrated.profile?.head,'fade');assert.equal(migrated.profile?.body,'athletic')});
test('Personality consistently changes XP, prices, heat, and outgoing firearm damage',()=>{const charismatic=quiet();charismatic.s.profile={...DEFAULT_PROFILE,name:'Ari',personality:'charismatic'};charismatic.xp('Street Rep',10);assert.equal(charismatic.s.xp['Street Rep'],12);const calculating=quiet();calculating.s.profile={...DEFAULT_PROFILE,name:'Sol',personality:'calculating'};assert.equal(calculating.price('bat'),89);const discreet=quiet();discreet.s.profile={...DEFAULT_PROFILE,name:'Rue',personality:'quiet'};discreet.raiseHeat(3);assert.equal(discreet.s.heat,2.75);const g=new Game({} as HTMLElement);g.session.notify=()=>{};g.session.save=async()=>{};g.session.s.profile={...DEFAULT_PROFILE,name:'Kai',personality:'fearless'};g.input={pitch:.3,yaw:0,keys:new Set()} as any;g.player={root:new T.Group()} as any;addItem(g.session.s,'pistol');addItem(g.session.s,'ammo9');g.session.s.weapon='pistol';g.aiming=true;g.shoot();assert.ok(Math.abs(g.bullets[0].damage-37.4)<.001)});
test('Authored GLB contains the full character and four playable animation tracks',async()=>{const b=readFileSync('public/models/mercer-resident.glb');const gltf=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength) as ArrayBuffer,'');assert.deepEqual(gltf.animations.map(a=>a.name),['Idle','Walk','Run','Attack']);assert.ok(gltf.scene.getObjectByName('ArmR'));assert.ok(gltf.scene.getObjectByName('LegL'));const bounds=new T.Box3().setFromObject(gltf.scene),size=bounds.getSize(new T.Vector3());assert.ok(size.y>1.7&&size.y<2);assert.ok(size.x<1)});
test('District geometry and physics allow sidewalk traversal and block buildings',async()=>{await RAPIER.init();(globalThis as any).document={pointerLockElement:null,createElement:()=>({width:1,height:1,getContext:()=>({fillRect(){},strokeRect(){},fillText(){}})})};const scene=new T.Scene(),district=createWorld(scene);assert.ok(district.solids.length>15);assert.ok(scene.children.length<=115,'District object budget includes Chapter 2 street details');const w=new RAPIER.World({x:0,y:-20,z:0});for(const b of district.solids)w.createCollider(RAPIER.ColliderDesc.cuboid(b.w/2,b.h/2,b.d/2).setTranslation(b.x,b.y,b.z));const body=w.createRigidBody(RAPIER.RigidBodyDesc.kinematicPositionBased().setTranslation(-10,1,22));const collider=w.createCollider(RAPIER.ColliderDesc.capsule(.55,.3),body);const ctrl=w.createCharacterController(.025);ctrl.enableAutostep(.3,.2,true);ctrl.enableSnapToGround(.4);function walk(dx:number,dz:number,frames:number){for(let i=0;i<frames;i++){ctrl.computeColliderMovement(collider,{x:dx,y:-20/60,z:dz});const p=body.translation(),d=ctrl.computedMovement();body.setNextKinematicTranslation({x:p.x+d.x,y:p.y+d.y,z:p.z+d.z});w.step()}}walk(0,-3.35/60,720);assert.ok(body.translation().z<-17,'Walked delivery route');body.setTranslation({x:-10,y:1,z:28},true);walk(-3.35/60,0,240);assert.ok(body.translation().x>-13.5,'Shop wall blocks player');assert.ok(body.translation().y>.8);w.free()});
test('Runtime nearest targeting, safe vehicle exit, boosting gates and spar reward',async()=>{const g=new Game({} as HTMLElement);g.session.notify=()=>{};g.session.save=async()=>{};g.session.onChange=()=>{};g.input={active:true,keys:new Set(),pressed:new Set(),clear(){},yaw:0} as any;g.player={root:new T.Group()} as any;g.warp=(x,z)=>{g.session.s.x=x;g.session.s.z=z};g.solids=[];g.vehicles=[{id:'bike1',x:0,z:0,yaw:0,condition:100,root:new T.Group(),speed:0,type:'bike'},{id:'sedan1',x:10,z:0,yaw:0,condition:100,root:new T.Group(),speed:0,type:'car'}];g.nearest='vehicle:sedan1';g.interact();assert.equal(g.riding,null,'Car theft is level gated');g.nearest='vehicle:bike1';g.interact();assert.equal((g.riding as {id:string}|null)?.id,'bike1');assert.ok(g.session.s.owned.includes('bike1'));g.exitVehicle();assert.equal(g.riding,null);assert.ok(Math.hypot(g.session.s.x,g.session.s.z)>2);g.fight=true;g.enemyHealth=20;g.actors=[{id:'dre',x:g.session.s.x,z:g.session.s.z+1,baseX:26,baseZ:-30,root:new T.Group(),timer:0} as any];g.hit(true);assert.equal(g.fight,false);assert.equal(g.session.s.cash,70);assert.equal(g.session.s.completed.spar,1);assert.ok(g.session.s.xp.Combat>0)});
test('Combat progression unlocks persistent weapons and rival rematches',()=>{const host=quiet();host.s.cash=500;host.buy('bat','pawn');assert.ok(!host.s.inventory.some(i=>i.id==='bat'));host.s.xp.Combat=xpFor(2);host.buy('bat','pawn');host.use('bat');assert.equal(host.s.weapon,'bat');assert.ok(validSave(host.s));const g=new Game({} as HTMLElement);g.session=host;g.sound.play=()=>{};g.player={root:new T.Group()} as any;g.fight=true;g.fightKind='rival';g.fightTarget='rico';g.enemyName='Rico';g.enemyHealth=20;g.actors=[{id:'rico',x:host.s.x,z:host.s.z+1,baseX:-48,baseZ:5,root:new T.Group(),timer:0} as any];g.hit(true);assert.equal(g.fight,false);assert.equal(host.s.completed['rival:rico'],1);assert.ok(host.s.completed['rivalReady:rico']>host.s.playtime);assert.ok(host.s.xp.Combat>xpFor(2))});
test('Street ladder gates supply, creates hot money, and requires a clean escape to stash',()=>{const h=quiet();h.s.cash=1000;h.s.xp.Hustling=xpFor(2);assert.equal(streetRank(h.s.xp.Hustling),1);h.supply('weed');assert.equal(h.s.inventory.find(i=>i.id==='weed')?.qty,3);const cash=h.s.cash;h.sellDrug('weed','cornerwest');assert.equal(h.s.cash,cash);assert.equal(h.s.dirtyCash,38);assert.ok(h.s.heat>0);h.stashCash();assert.equal(h.s.cash,cash);h.s.heat=0;h.stashCash();assert.equal(h.s.dirtyCash,0);assert.equal(h.s.cash,cash+38);assert.ok(validSave(h.s))});
test('Crime tiers are deterministic and kingpin bank scores trigger five stars',()=>{const h=quiet();addItem(h.s,'lockpick');h.s.xp.Hustling=xpFor(2);h.robbery('home');assert.equal(h.s.dirtyCash,220);assert.equal(h.s.heat,3);const locked=quiet();locked.s.xp.Hustling=xpFor(10);locked.robbery('bank');assert.equal(locked.s.dirtyCash,0);addItem(locked.s,'pistol');locked.s.weapon='pistol';locked.robbery('bank');assert.equal(locked.s.dirtyCash,2500);assert.equal(locked.s.heat,5)});
test('Kingpin wholesale runs require capital and produce a maximum-response score',()=>{const h=quiet();h.s.xp.Hustling=xpFor(10);h.s.cash=1199;h.kingpinRun();assert.equal(h.s.dirtyCash,0);h.s.cash=1200;h.kingpinRun();assert.equal(h.s.cash,0);assert.equal(h.s.dirtyCash,2800);assert.equal(h.s.heat,5);assert.equal(h.s.completed['street:shipments'],1)});
test('Manual firearm aim consumes ammo and launches a physical projectile without aim assist',()=>{const g=new Game({} as HTMLElement);g.session.notify=()=>{};g.session.save=async()=>{};g.input={pitch:.3,yaw:0,keys:new Set()} as any;g.player={root:new T.Group()} as any;addItem(g.session.s,'pistol');addItem(g.session.s,'ammo9');g.session.s.weapon='pistol';g.aiming=false;g.shoot();assert.equal(g.ammoCount(),1);assert.equal(g.bullets.length,0);g.aiming=true;g.shoot();assert.equal(g.ammoCount(),0);assert.equal(g.bullets.length,1);assert.ok(g.bullets[0].velocity.length()>50);assert.ok(g.session.s.heat>=3)});
test('Owned-vehicle race follows every checkpoint and pays deterministic progression',()=>{const g=new Game({} as HTMLElement);g.session.notify=()=>{};g.session.save=async()=>{};g.session.onChange=()=>{};g.sound.play=()=>{};g.input={yaw:0} as any;g.player={root:new T.Group()} as any;g.session.s.owned=['bike1'];g.vehicles=[{id:'bike1',x:0,z:0,yaw:0,condition:100,root:new T.Group(),speed:0,type:'bike'}];g.startRace('bike');assert.equal(g.raceMode,'bike');for(const p of g.raceCheckpoints){g.riding!.x=p.x;g.riding!.z=p.z;g.updateRace(1)}assert.equal(g.raceMode,null);assert.equal(g.session.s.completed['activity:bikeRace'],1);assert.ok(g.session.s.cash>40);assert.ok(g.session.s.xp.Boosting>=70)});

import {chapterChoice,relaySwitch,storyState} from '../game/simulation/story';
import {migrateSave} from '../game/simulation/state';
import {storyActions} from '../game/simulation/story-panels';
function reachFinal(s:ReturnType<typeof fresh>,cash=false,advance=true){for(const [stage,choice] of [[0,'help'],[1,'believe'],[2,'investigate']] as const)assert.ok(chapterChoice(s,stage,choice).ok);assert.equal(relaySwitch(s,'relay').ok,false);for(const key of ['ground','bypass','relay'])relaySwitch(s,key);assert.equal(storyState(s).stage,4);assert.ok(chapterChoice(s,4,cash?'cash':'copy').ok);assert.ok(chapterChoice(s,5,advance?'accept':'refuse').ok);assert.ok(chapterChoice(s,6,'honest').ok)}
test('Chapter 1 completes on all three routes; replayed choices never repay',()=>{for(const route of ['neighbors','bishop','bury']){const s=fresh();reachFinal(s);assert.ok(chapterChoice(s,7,route).ok);const balance=s.cash;assert.equal(chapterChoice(s,7,route).ok,false);assert.equal(s.cash,balance);assert.equal(storyState(s).stage,8);assert.ok(storyState(s).flags.includes('chapter_one_complete'));assert.ok(storyState(s).evidence.includes('ledger'));assert.ok(validSave(s))}});
test('Chapter choices change real prices and Bishop debt can be settled once',()=>{const host=quiet();reachFinal(host.s);chapterChoice(host.s,7,'neighbors');assert.equal(host.price('meal','deli'),11);assert.ok(storyState(host.s).flags.includes('bishop_collecting'));const action=storyActions(host,'bishop').find(a=>a.label.includes('Repay'))!;const before=host.s.cash;action.run();assert.equal(host.s.cash,before-90);action.run();assert.equal(host.s.cash,before-90);assert.ok(!storyState(host.s).flags.includes('bishop_collecting'));const other=quiet();reachFinal(other.s,true);chapterChoice(other.s,7,'bishop');assert.equal(other.price('meal','deli'),14);assert.ok(!storyState(other.s).evidence.includes('ledger'));assert.ok(!storyState(other.s).flags.includes('bishop_debt'))});
test('Optional favors consume resources and grant their rewards exactly once',()=>{const host=quiet();const fire=(p:string,text:string)=>{const a=storyActions(host,p).find(a=>a.label.includes(text));assert.ok(a);a!.run();return a!};fire('food','SIDE QUEST');addItem(host.s,'water');const action=fire('food','Give Rosa');assert.equal(host.s.inventory.some(i=>i.id==='water'),false);const xp=host.s.xp['Street Rep'];action.run();assert.equal(host.s.xp['Street Rep'],xp);assert.equal(host.price('meal','food'),11);host.s.completed.spar=4;fire('court','SIDE QUEST');assert.ok(!storyActions(host,'court').some(a=>a.label.includes('Check in')));host.s.completed.spar=5;const dre=fire('court','Check in');const cash=host.s.cash;dre.run();assert.equal(host.s.cash,cash);assert.equal(storyState(host.s).side.dre,2)});
test('Existing saves keep cash, XP, completed fights and inventory during story migration',async()=>{const old=fresh();delete old.story;old.cash=777;old.xp.Combat=300;old.completed.spar=4;addItem(old,'water',2);assert.ok(validSave(old));const migrated=migrateSave(old);assert.equal(storyState(migrated).stage,0);assert.equal(migrated.cash,777);assert.equal(migrated.xp.Combat,300);assert.equal(migrated.completed.spar,4);assert.deepEqual(migrated.inventory,old.inventory);reachFinal(migrated);chapterChoice(migrated,7,'bury');await saveGame(migrated);assert.deepEqual(await loadSave(),migrated);assert.ok(!validSave({...migrated,story:{revision:1}}))});

import {chapterTwoChoice,recorderActions} from '../game/simulation/chapter-two';
import {chapterThreeChoice,chapterThreeActions} from '../game/simulation/chapter-three';
import {chapterFourChoice,chapterFourActions} from '../game/simulation/chapter-four';
test('Chapter 2: prior relationships gate access; every ending persists without duplicate rewards',async()=>{for(const ending of ['publish','deal','protect']){const s=fresh();reachFinal(s);chapterChoice(s,7,'neighbors');const before=s.cash;assert.ok(chapterTwoChoice(s,8,'help'));assert.ok(chapterTwoChoice(s,9,'connections'));assert.ok(chapterTwoChoice(s,10,'release'));assert.equal(s.heat,0);assert.ok(chapterTwoChoice(s,11,'share'));assert.ok(chapterTwoChoice(s,12,'trace'));assert.ok(chapterTwoChoice(s,13,ending));const cash=s.cash;assert.ok(!chapterTwoChoice(s,13,ending));assert.equal(s.cash,cash);assert.ok(cash>=before+140);assert.equal(storyState(s).stage,14);assert.ok(validSave(s));await saveGame(s);assert.deepEqual(await loadSave(),s)}});
test('Chapter 2: lost evidence leaves a signposted force route; recovered supply changes prices',()=>{const h=quiet();reachFinal(h.s,true,false);chapterChoice(h.s,7,'bury');chapterTwoChoice(h.s,8,'help');assert.ok(!chapterTwoChoice(h.s,9,'connections'));assert.ok(chapterTwoChoice(h.s,9,'press'));assert.ok(!chapterTwoChoice(h.s,10,'release'));assert.ok(chapterTwoChoice(h.s,10,'force'));assert.equal(h.s.heat,1);chapterTwoChoice(h.s,11,'market');assert.equal(h.price('meal','deli'),11);assert.ok(storyState(h.s).flags.includes('shipment_restored'))});
test('Chapter 2: recorder favor consumes one part and recovers late evidence once',()=>{const h=quiet();reachFinal(h.s);chapterChoice(h.s,7,'neighbors');for(const [stage,choice] of [[8,'help'],[9,'connections'],[10,'release'],[11,'share'],[12,'trace']] as const)chapterTwoChoice(h.s,stage,choice);recorderActions(h,'garage')[0].run();addItem(h.s,'scrap');const a=recorderActions(h,'garage')[0];a.run();const cash=h.s.cash;a.run();assert.equal(h.s.cash,cash);assert.ok(storyState(h.s).evidence.includes('recording'));assert.ok(!h.s.inventory.some(i=>i.id==='scrap'))});
function reachChapter3Start(s:ReturnType<typeof fresh>){reachFinal(s);chapterChoice(s,7,'neighbors');for(const [stage,choice] of [[8,'help'],[9,'connections'],[10,'release'],[11,'share'],[12,'trace'],[13,'protect']] as const)assert.ok(chapterTwoChoice(s,stage,choice).valueOf());}
test('Chapter 3 completes all routes once and preserves old-save validity',()=>{for(const ending of ['save','preserve','expose'] as const){const s=fresh();reachChapter3Start(s);assert.ok(chapterThreeChoice(s,14,'testify').ok);assert.ok(chapterThreeChoice(s,15,'back').ok);assert.ok(chapterThreeChoice(s,16,'accept').ok);assert.ok(chapterThreeChoice(s,17,'compare').ok);assert.ok(chapterThreeChoice(s,18,ending).ok);const cash=s.cash;assert.equal(chapterThreeChoice(s,18,ending).ok,false);assert.equal(s.cash,cash);assert.equal(storyState(s).stage,19);assert.ok(storyState(s).flags.includes('chapter_three_complete'));assert.ok(validSave(s))}});
function reachChapter4Start(s:ReturnType<typeof fresh>){reachChapter3Start(s);for(const [stage,choice] of [[14,'testify'],[15,'back'],[16,'accept'],[17,'compare'],[18,'save']] as const)assert.ok(chapterThreeChoice(s,stage,choice).valueOf());}
test('Chapter 4 completes all routes once and old saves reach it without reset',async()=>{for(const ending of ['protect','publish','contact'] as const){const s=fresh();reachChapter4Start(s);assert.ok(chapterFourChoice(s,19,'listen').ok);assert.ok(chapterFourChoice(s,20,'assembly').ok);assert.ok(chapterFourChoice(s,21,'records').ok);assert.ok(chapterFourChoice(s,22,'tell').ok);assert.ok(chapterFourChoice(s,23,ending).ok);const cash=s.cash;assert.equal(chapterFourChoice(s,23,ending).ok,false);assert.equal(s.cash,cash);assert.equal(storyState(s).stage,24);assert.ok(storyState(s).flags.includes('chapter_four_complete'));assert.ok(validSave(s));await saveGame(s);assert.deepEqual(await loadSave(),s)}});
test('Chapter 4 evidence routes: favors gate strong proof; thin-proof fallback still completes',()=>{const h=quiet();reachChapter4Start(h.s);assert.ok(chapterFourChoice(h.s,19,'listen').ok);assert.ok(chapterFourChoice(h.s,20,'photo').ok);assert.ok(storyState(h.s).evidence.includes('missing_person'));assert.ok(!storyState(h.s).evidence.includes('envelope_scan'));const rich=quiet();reachChapter4Start(rich.s);storyState(rich.s).side.keepsake=3;storyState(rich.s).side.recorder=2;assert.ok(chapterFourChoice(rich.s,19,'listen').ok);assert.ok(chapterFourChoice(rich.s,20,'photo').ok);assert.ok(storyState(rich.s).evidence.includes('envelope_scan'));assert.equal(chapterFourChoice(rich.s,20,'recordings').ok,false);assert.ok(storyState(rich.s).evidence.includes('theo_recording')===false);for(const [stage,choice] of [[21,'door'],[22,'quiet'],[23,'protect']] as const)assert.ok(chapterFourChoice(rich.s,stage,choice).ok);assert.ok(storyState(rich.s).flags.includes('theo_protected'));assert.ok(storyState(rich.s).evidence.includes('envelope_scan'))});
test('Chapter 4 final decision: contact requires Vale access, publish raises heat with proof',()=>{const noAccess=quiet();reachChapter4Start(noAccess.s);for(const [stage,choice] of [[19,'listen'],[20,'assembly'],[21,'catalog'],[22,'steady']] as const)assert.ok(chapterFourChoice(noAccess.s,stage,choice).valueOf());storyState(noAccess.s).flags=storyState(noAccess.s).flags.filter(f=>!['vale_role','vale_infiltrate'].includes(f));assert.equal(chapterFourChoice(noAccess.s,23,'contact').ok,false);const published=quiet();reachChapter4Start(published.s);storyState(published.s).side.recorder=2;for(const [stage,choice] of [[19,'listen'],[20,'recordings'],[21,'door'],[22,'tell']] as const)assert.ok(chapterFourChoice(published.s,stage,choice).valueOf());const heatBefore=published.s.heat;assert.ok(chapterFourChoice(published.s,23,'publish').ok);assert.ok(published.s.heat>=Math.max(1,heatBefore));assert.ok(storyState(published.s).flags.includes('theo_public'))});
test('Chapter 4 optional favors consume inputs and pay exactly once',()=>{const h=quiet();reachChapter4Start(h.s);let action=chapterFourActions(h,'meeting').find(a=>a.label.includes('SIDE QUEST'));assert.ok(action);action!.run();assert.equal(storyState(h.s).side.poster,1);action=chapterFourActions(h,'clothes').find(a=>a.label.includes('marker'));assert.ok(action);action!.run();assert.equal(storyState(h.s).side.poster,2);action=chapterFourActions(h,'meeting').find(a=>a.label.includes('Write Theo'));assert.ok(action);const cash=h.s.cash;action!.run();assert.equal(storyState(h.s).side.poster,3);assert.equal(h.s.cash,cash+30);assert.ok(!chapterFourActions(h,'meeting').some(a=>a.label.includes('Write Theo')));const w=quiet();reachChapter4Start(w.s);action=chapterFourActions(w,'garage').find(a=>a.label.includes('SIDE QUEST'));assert.ok(action);action!.run();action=chapterFourActions(w,'meeting').find(a=>a.label.includes('Ask Jay'));assert.ok(action);action!.run();assert.equal(storyState(w.s).side.eyewitness,2);const m=quiet();reachChapter4Start(m.s);action=chapterFourActions(m,'bank').find(a=>a.label.includes('SIDE QUEST'));assert.ok(action);action!.run();action=chapterFourActions(m,'home').find(a=>a.label.includes('Walk June'));assert.ok(action);action!.run();assert.equal(storyState(m.s).side.memorywalk,2);assert.ok(validSave(h.s)&&validSave(w.s)&&validSave(m.s))});
test('Chapter 3 evidence route exposes attendance and optional favors stay additive',()=>{const h=quiet();reachChapter3Start(h.s);assert.ok(chapterThreeChoice(h.s,14,'observe').ok);assert.ok(chapterThreeChoice(h.s,15,'document').ok);assert.ok(chapterThreeChoice(h.s,16,'infiltrate').ok);assert.ok(chapterThreeChoice(h.s,17,'compare').ok);assert.ok(chapterThreeChoice(h.s,18,'expose').ok);assert.equal(h.s.heat,1);assert.ok(storyState(h.s).evidence.includes('attendance'));assert.ok(storyState(h.s).evidence.includes('citizen_files'));assert.ok(storyState(h.s).evidence.includes('permit_order'));const side=quiet();reachChapter3Start(side.s);let action=chapterThreeActions(side,'clothes').find(a=>a.label.includes('SIDE QUEST'));assert.ok(action);action!.run();addItem(side.s,'scrap');action=chapterThreeActions(side,'clothes').find(a=>a.label.includes('Repair Nia'));assert.ok(action);action!.run();assert.equal(storyState(side.s).side.merchant,2);action=chapterThreeActions(side,'bank').find(a=>a.label.includes('SIDE QUEST'));assert.ok(action);action!.run();action=chapterThreeActions(side,'garage').find(a=>a.label.includes('Compare records'));assert.ok(action);action!.run();action=chapterThreeActions(side,'meeting').find(a=>a.label.includes('Build the tenant line'));assert.ok(action);action!.run();action=chapterThreeActions(side,'home').find(a=>a.label.includes('Print the independent'));assert.ok(action);action!.run();assert.equal(storyState(side.s).side.tenantline,2);assert.ok(validSave(side.s))});
