'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Check,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Game} from '@/game/render/runtime';
import {BACKGROUNDS,BODY_TYPES,BUILDS,DEFAULT_PROFILE,FACE_SHAPES,HAIR_COLORS,HEAD_STYLES,PERSONALITIES,PRONOUNS,SKIN_TONES,STYLES,choice,type CharacterProfile} from '@/game/simulation/profile';

const STEPS=[['01','Identity','What the block calls you'],['02','Appearance','How you enter a room'],['03','Background','What you bring with you'],['04','Personality','How you move through pressure'],['05','Review','The person stepping outside']] as const;
type Props={game:Game;onComplete:()=>void;onCancel:()=>void};
export function CharacterCreator({game,onComplete,onCancel}:Props){
 const[step,setStep]=useState(0),[profile,setProfile]=useState<CharacterProfile>({...DEFAULT_PROFILE});
 const set=<K extends keyof CharacterProfile>(key:K,value:CharacterProfile[K])=>setProfile(p=>({...p,[key]:value}));
 useEffect(()=>{game.setCreator(true);game.previewAppearance(profile)},[game,profile]);
 const origin=choice(BACKGROUNDS,profile.background),nature=choice(PERSONALITIES,profile.personality);
 const next=()=>{if(step<4)setStep(s=>s+1);else if(game.session.createProfile(profile)){game.setCreator(false);game.start();onComplete()}};
 const cancel=()=>{game.setCreator(false);onCancel()};
 const valid=profile.name.trim().length>=2;
 return <section className="creator-shell" aria-label="Character creation">
  <header className="creator-header"><div><span>SAINT MERCER INTAKE / DISTRICT 09</span><strong>WHO ARE YOU WHEN NOBODY IS WATCHING?</strong></div><button onClick={cancel}><ArrowLeft size={15}/> RETURN TO TITLE</button></header>
  <div className="creator-layout">
   <nav className="creator-steps" aria-label="Creation progress">{STEPS.map((s,i)=><button key={s[1]} onClick={()=>i<=step&&setStep(i)} className={i===step?'active':i<step?'done':''} disabled={i>step}><b>{i<step?'✓':s[0]}</b><span><strong>{s[1]}</strong><small>{s[2]}</small></span></button>)}</nav>
   <div className="creator-panel">
    <div className="creator-kicker">STEP {step+1} OF 5 · {STEPS[step][1].toUpperCase()}</div>
    {step===0&&<><h1>Put a name on it.</h1><p className="creator-lede">This is the name Saint Mercer remembers. Keep it yours.</p><label className="name-field"><span>YOUR NAME</span><input autoFocus maxLength={18} value={profile.name} onChange={e=>set('name',e.target.value.replace(/[^a-zA-Z0-9 '\-]/g,''))} placeholder="Enter a name"/><small>{profile.name.trim().length<2?'At least 2 characters.':`${profile.name.length} / 18`}</small></label><div className="choice-section"><h2>Pronouns</h2><div className="compact-choices">{PRONOUNS.map(x=><button key={x.id} onClick={()=>set('pronouns',x.id)} className={profile.pronouns===x.id?'selected':''}>{x.label}{profile.pronouns===x.id&&<Check size={15}/>}</button>)}</div></div></>}
    {step===1&&<><h1>Make the first impression.</h1><p className="creator-lede">Your full-body preview stays live on the right. Pick a face, head, and physique, then watch the resident model update before you commit.</p><div className="choice-section"><h2>Skin tone</h2><div className="swatch-row">{SKIN_TONES.map(x=><button key={x.id} onClick={()=>set('skin',x.id)} className={profile.skin===x.id?'selected':''}><i style={{background:x.color}}/><span>{x.label}</span></button>)}</div></div><div className="choice-section"><h2>Hair color</h2><div className="swatch-row">{HAIR_COLORS.map(x=><button key={x.id} onClick={()=>set('hair',x.id)} className={profile.hair===x.id?'selected':''}><i style={{background:x.color}}/><span>{x.label}</span></button>)}</div></div><div className="choice-section"><h2>Face</h2><div className="compact-choices three">{FACE_SHAPES.map(x=><button key={x.id} onClick={()=>set('face',x.id)} className={(profile.face||DEFAULT_PROFILE.face)===x.id?'selected':''}><span>{x.label}</span><small>{x.note}</small></button>)}</div></div><div className="choice-section"><h2>Head / hair shape</h2><div className="compact-choices three">{HEAD_STYLES.map(x=><button key={x.id} onClick={()=>set('head',x.id)} className={(profile.head||DEFAULT_PROFILE.head)===x.id?'selected':''}><span>{x.label}</span><small>{x.note}</small></button>)}</div></div><div className="choice-section"><h2>Physique</h2><div className="compact-choices three">{BODY_TYPES.map(x=><button key={x.id} onClick={()=>set('body',x.id)} className={(profile.body||DEFAULT_PROFILE.body)===x.id?'selected':''}><span>{x.label}</span><small>{x.note}</small></button>)}</div></div><div className="choice-section"><h2>Height / frame</h2><div className="compact-choices four">{BUILDS.map(x=><button key={x.id} onClick={()=>set('build',x.id)} className={profile.build===x.id?'selected':''}><span>{x.label}</span><small>{x.note}</small></button>)}</div></div><div className="choice-section"><h2>Street style</h2><div className="swatch-row">{STYLES.map(x=><button key={x.id} onClick={()=>set('style',x.id)} className={profile.style===x.id?'selected':''}><i style={{background:x.color}}/><span>{x.label}</span></button>)}</div></div></>}
    {step===2&&<><h1>Everybody comes from somewhere.</h1><p className="creator-lede">Your background changes your opening resources and the first skill you bring to Saint Mercer.</p><div className="origin-grid">{BACKGROUNDS.map(x=><button key={x.id} onClick={()=>set('background',x.id)} className={profile.background===x.id?'selected':''}><span>{x.tag}</span><strong>{x.label}</strong><p>{x.description}</p><b>{x.effect}</b>{profile.background===x.id&&<Check size={18}/>}</button>)}</div></>}
    {step===3&&<><h1>What do people learn about you?</h1><p className="creator-lede">This trait keeps shaping rewards, prices, combat, or police exposure for the whole game.</p><div className="origin-grid personality-grid">{PERSONALITIES.map(x=><button key={x.id} onClick={()=>set('personality',x.id)} className={profile.personality===x.id?'selected':''}><span>{x.tag}</span><strong>{x.label}</strong><p>{x.description}</p><b>{x.effect}</b>{profile.personality===x.id&&<Check size={18}/>}</button>)}</div></>}
    {step===4&&<><h1>This is who steps outside.</h1><p className="creator-lede">Creation is permanent for this story. Every choice below travels with the save.</p><div className="review-name"><span>SAINT MERCER RESIDENT / 09</span><strong>{profile.name.trim()||'Unnamed'}</strong><small>{choice(PRONOUNS,profile.pronouns).label} · {choice(BUILDS,profile.build).label} build · {choice(STYLES,profile.style).label} style</small></div><div className="review-grid"><article><span>BACKGROUND</span><strong>{origin.label}</strong><p>{origin.description}</p><b>{origin.effect}</b><button onClick={()=>setStep(2)}>CHANGE</button></article><article><span>PERSONALITY</span><strong>{nature.label}</strong><p>{nature.description}</p><b>{nature.effect}</b><button onClick={()=>setStep(3)}>CHANGE</button></article></div><div className="consequence-note"><strong>THE WORLD KEEPS RECEIPTS.</strong><span>People will know your name. Your build and colors remain on your model. Your origin changes the opening. Your personality changes the rules that follow.</span></div></>}
    <footer className="creator-footer"><button className="creator-back" onClick={()=>step?setStep(s=>s-1):cancel()}><ArrowLeft size={16}/>{step?'BACK':'TITLE'}</button><span>{String(step+1).padStart(2,'0')} / 05</span><Button className="creator-next" disabled={!valid} onClick={next}>{step===4?'BEGIN YOUR STORY':'CONTINUE'}{step===4?<Check size={18}/>:<ChevronRight size={18}/>}</Button></footer>
   </div>
   <aside className="creator-preview"><div className="creator-stage-meta"><span>LIVE / FULL-BODY MODEL</span><small>AUTO-ROTATING PREVIEW</small></div><div className="creator-preview-copy"><small>{choice(SKIN_TONES,profile.skin).label.toUpperCase()} · {choice(HAIR_COLORS,profile.hair).label.toUpperCase()}</small><strong>{profile.name.trim()||'YOUR NAME'}</strong><p>{choice(FACE_SHAPES,profile.face||DEFAULT_PROFILE.face!).label} face · {choice(HEAD_STYLES,profile.head||DEFAULT_PROFILE.head!).label}</p><p>{choice(BODY_TYPES,profile.body||DEFAULT_PROFILE.body!).label} physique · {choice(BUILDS,profile.build).label} frame</p></div></aside>
  </div>
 </section>
}
