'use client';
import {useState} from 'react';
import {ArrowRight,Car,Coins,Crosshair,Gamepad2,Map,Shield,Users,Zap} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Game} from '@/game/render/runtime';
const LESSONS=[
 {icon:Map,title:'WELCOME TO SAINT MERCER',tag:'THE POINT OF HOODSCAPE',text:'There is no single correct life. Build skills, make money, earn relationships, own rides, explore, compete, commit crimes, or follow the conspiracy. The city reacts to what you choose.',items:['Your story is optional—not a campaign lock.','Every skill reaches level 99.','Your account keeps one persistent character.']},
 {icon:Map,title:'CHOOSE YOUR FIRST DIRECTION',tag:'STORY OR SANDBOX',text:'This only changes what the HUD recommends. You can switch paths later and every mission remains available.',items:[]},
 {icon:Gamepad2,title:'MOVE LIKE YOU LIVE HERE',tag:'MOVEMENT + CAMERA',text:'Walk the block before chasing money. The camera follows your direction and the minimap rotates with you.',items:['WASD / left stick: move','Mouse / drag: look · wheel: zoom','Shift: sprint · Space: dodge']},
 {icon:Users,title:'TALK, WORK, AND LISTEN',tag:'PEOPLE OPEN THE CITY',text:'Walk close to a person or marked place and interact. Jobs repeat; side quests remember promises; some choices unlock new NPCs, areas, prices, and mission lines.',items:['E / USE: interact','M: journal and mission lines','Gold markers: current lead · white markers: places']},
 {icon:Zap,title:'BUILD A LIFE, NOT A LOADOUT',tag:'PROGRESSION + ECONOMY',text:'Combat, Fitness, Hustling, Boosting, and Street Rep level independently. Work, race, train, trade, bank money, buy gear, and own vehicles.',items:['I: backpack · P: skills','Banked cash survives arrest','Background and personality bonuses stay active']},
 {icon:Crosshair,title:'THE CITY KEEPS RECEIPTS',tag:'CRIME + CONSEQUENCES',text:'Witnesses call police, Heat climbs to five stars, hot cash must be stashed, rivals remember losses, and story relationships alter future opportunities.',items:['Right mouse: aim · left click / J: attack','Q: block · K: heavy attack','Lose sight before Heat drains']},
 {icon:Shield,title:'PVP IS A CHOICE—UNTIL YOU ENTER',tag:'SHARED WORLD RULES',text:'Other players appear live in Saint Mercer. Toggle PvP Ready, then enter a red combat district. Damage only counts when both players are Ready inside the same zone.',items:['SAFE: other players cannot damage you','READY: combat enabled in red zones','A knockout respawns you safe at The Towers']},
 {icon:Car,title:'THE CITY IS BIGGER THAN MISSIONS',tag:'ACTIVITIES + LIVE DECISIONS',text:'Court games, street and bike races, alley dice, rival challenges, jobs, favors, and discoveries are independent ways to progress. Timed choices do not pause the world.',items:['Activities award skill XP and records','Some NPCs and districts unlock through side lines','You can ignore the main story indefinitely']},
 {icon:Coins,title:'MAKE YOUR NAME MEAN SOMETHING',tag:'YOU ARE READY',text:'Pick a lead or walk in the opposite direction. Saint Mercer will keep moving either way.',items:['Story path: begin with Malik at Mercer Market','Sandbox path: choose any marker or player','Tutorial can be replayed from the pause menu']}
] as const;
export function TutorialOverlay({game,onDone}:{game:Game;onDone:()=>void}){const[step,setStep]=useState(Math.min(8,game.session.s.tutorial?.step||0)),lesson=LESSONS[step],Icon=lesson.icon;const record=(next:number,complete=false)=>{game.session.s.tutorial={step:next,complete};void game.session.save(false)};const finish=()=>{record(8,true);onDone()};return <section className="tutorial-overlay"><div className="tutorial-progress">{LESSONS.map((_,i)=><i key={i} className={i<=step?'active':''}/>)}</div><article className="tutorial-card"><header><span><Icon size={19}/>{lesson.tag}</span><button onClick={finish}>SKIP TUTORIAL</button></header><h2>{lesson.title}</h2><p>{lesson.text}</p>{step===1?<div className="path-choice"><button className={game.session.s.path==='story'?'selected':''} onClick={()=>{game.session.s.path='story';record(step)}}><strong>FOLLOW THE SIGNAL</strong><span>Keep the conspiracy storyline as your recommended lead.</span></button><button className={game.session.s.path==='sandbox'?'selected':''} onClick={()=>{game.session.s.path='sandbox';record(step)}}><strong>MAKE MY OWN WAY</strong><span>Start free roam with jobs, skills, activities, and players.</span></button></div>:<ul>{lesson.items.map(x=><li key={x}>{x}</li>)}</ul>}<footer><span>FIELD GUIDE {String(step+1).padStart(2,'0')} / {LESSONS.length}</span><Button disabled={step===1&&!game.session.s.path} onClick={()=>{if(step===8)finish();else{const next=step+1;record(next);setStep(next)}}}>{step===8?'ENTER SAINT MERCER':'NEXT'}<ArrowRight size={17}/></Button></footer></article></section>}
