import type {Save} from './state';
import type {Session,Action} from './session';
import {removeItem} from './state';
import {CHAPTER_TWO,storyState,remember,record,addEvidence} from './story';
export function chapterTwoChoice(s:Save,stage:number,choice:string){const st=storyState(s);if(st.stage!==stage||st.choices[String(stage)])return false;const options:Record<number,string[]>={8:['help'],9:['connections','press'],10:['release','force'],11:['share','market'],12:['trace'],13:['publish','deal','protect']};if(!options[stage]?.includes(choice))return false;
 const access=st.relationships.bishop.trust>=20||st.evidence.includes('ledger')||st.side.dre===2;
 if(choice==='connections'&&!access)return false;
 if(choice==='release'&&!st.flags.includes('delivery_access'))return false;
 let text='',reward=0;const flag=(v:string)=>{if(!st.flags.includes(v))st.flags.push(v)};
 if(stage===8){flag('shipment_missing');text=st.flags.includes('route_bishop')?'Malik keeps his distance. “You know Bishop. Ask him why my food truck is sitting in his loading bay.”':'Malik shows you an empty delivery receipt. “They sell us protection, then stop the trucks. Bishop knows where it went.”';remember(st,'malik','Investigated the missing food shipment.',5,5)}
 if(stage===9){if(choice==='connections'){flag('delivery_access');remember(st,'bishop','Used an existing connection to negotiate the shipment’s release.',5,10);text=st.side.dre===2?'Dre’s promise counts. Bishop signs a release rather than make an enemy of the whole court.':'Bishop signs the release. “My name gets your truck out. Remember that.”'}else{remember(st,'bishop','Challenged him over the missing shipment.',-5,10,10);text='“East loading bay. The seal stays locked.” Bishop lets the location slip, but refuses to authorize release. Breaking the seal could bring police attention.'}}
 if(stage===10){addEvidence(st,'dispatch');flag('shipment_carried');if(choice==='force'){s.heat=Math.max(s.heat,1);text='You break the monitored seal. An alarm reports suspicious activity. Inside, the recovery crew’s invoice names the same account that paid to divert the truck.'}else text='The release code opens the cargo cage. You recover the shipment and photograph two invoices: both sides of the dispute are paid from account 0317.';text+=' The sealed supplies are secured for delivery to Rosa.'}
 if(stage===11){flag('shipment_restored');st.flags=st.flags.filter(f=>f!=='shipment_carried');if(choice==='share'){flag('community_meals');remember(st,'rosa','Shared recovered supplies with struggling households.',20,10);remember(st,'june','Made sure the tenants could eat.',10);text='Rosa organizes a meal table. Sunday’s food is now another 10% cheaper. Some of Malik’s shelves will stay thin, but nobody goes hungry.'}else{flag('market_priority');remember(st,'malik','Restocked his market before distributing the food.',20,10);remember(st,'rosa','Put the market ahead of the community meal table.',-5);reward=50;text='Malik pays $50 for the returned stock. His market gives you an additional 10% off. Rosa keeps a smaller supply for the kitchen.'}}
 if(stage===12){if(st.side.recorder===2){addEvidence(st,'recording');text='The recorder you repaired preserves the full order: “Controlled shortage. Maintain baseline. Vale’s hearing goes ahead.” Ruiz offers to testify.'}else{text='Ruiz extracts the account and hearing time, but the failing recorder loses the dispatcher’s name. “We can still fix my recorder before the meeting. Bring one salvaged part.”'}text+=' The tenants are gathering by the noticeboard outside the Towers.'}
 if(stage===13){reward=140;const proof=st.evidence.includes('ledger')||st.evidence.includes('recording');if(choice==='publish'){flag('public_case');remember(st,'malik','Brought the paymaster evidence to the tenant meeting.',25,15);remember(st,'bishop','Exposed the protection scheme publicly.',-20,10,20);text=proof?'The tenants circulate documentary proof. Malik restores a neighbor’s welcome; his old Bishop surcharge ends. The hearing must address your evidence.':'The invoices establish a link, but not who gave the orders. The tenants demand answers anyway. Malik ends his old Bishop surcharge.';st.flags=st.flags.filter(f=>f!=='route_bishop')}
 if(choice==='deal'){flag('shipment_truce');st.flags=st.flags.filter(f=>!['bishop_collecting','bishop_debt'].includes(f));remember(st,'bishop','Negotiated a supply truce instead of public exposure.',20,15);remember(st,'june','Traded public accountability for short-term relief.',-10,0,10);reward+=60;text='Bishop guarantees deliveries and forgives the outstanding advance. He pays $60 extra for discretion. June wanted the names made public; she will remember the compromise.'}
 if(choice==='protect'){flag('source_protected');remember(st,'ruiz','Protected his identity while preserving the investigation.',25,10);remember(st,'june','Kept the witness safe for the hearing.',15);text='The tenants release an anonymized account. Ruiz stays out of the spotlight and offers $5 repairs. The strongest evidence remains yours to present at the hearing.'}
 flag('chapter_two_complete');text+=st.side.dre===2?' Dre stands with June as the meeting ends.':'';text+=' A formal invitation arrives: Saint Mercer Initiative public hearing. Signed, Director Vale.'}
 st.choices[String(stage)]=choice;st.stage++;s.cash+=reward;record(st,CHAPTER_TWO[stage-8].title,text);return true;
}
export function chapterTwoPanel(host:Session){const st=storyState(host.s),stage=st.stage;if(stage<8||stage>13)return;const node=CHAPTER_TWO[stage-8],access=st.relationships.bishop.trust>=20||st.evidence.includes('ledger')||st.side.dre===2;
 const scripts:Record<number,{text:string;choices:{id:string;label:string;disabled?:boolean}[]}>= {
 8:{text:'Malik’s delivery never arrived. A protection invoice did. “Whatever happened between us, people still need to eat. Help me find that truck.”',choices:[{id:'help',label:'Find out who stopped the delivery.'}]},
 9:{text:`“A held shipment isn’t a stolen shipment,” Bishop says. ${access?'Your prior evidence or relationships give you something to negotiate with.':'Without a trusted connection or the old ledger, he won’t authorize a release.'}`,choices:[{id:'connections',label:'Use your connection or evidence to get a release.',disabled:!access},{id:'press',label:'Demand the location. Find your own way in.'}]},
 10:{text:st.flags.includes('delivery_access')?'The cargo cage is locked. Your signed release includes a working code.':'The cargo cage is locked and monitored. Breaking the seal will raise Heat. You can leave and prepare before committing.',choices:[{id:'release',label:'Use the release code and recover the supplies.',disabled:!st.flags.includes('delivery_access')},{id:'force',label:'Break the monitored seal. Risk police attention.'}]},
 11:{text:'Rosa checks the recovered supplies. “Enough for the market, or a decent start for every kitchen on this block. Who gets priority?”',choices:[{id:'share',label:'Set up community meals. Lower Sunday’s prices.'},{id:'market',label:'Restock Malik first. Earn $50 and a market discount.'}]},
 12:{text:'Ruiz recognizes the dispatcher’s account. “They paid to stop the truck, then paid somebody else to rescue it. Let me pull the recording. The old machine might lose the voice.”',choices:[{id:'trace',label:'Trace the recording and take the findings to the meeting.'}]},
 13:{text:`The noticeboard is surrounded by tenants. June asks who paid to make them hungry. ${st.evidence.includes('ledger')||st.evidence.includes('recording')?'You have stronger evidence beyond the shipment invoices.':'Your invoices show the connection; the original ledger and clear recording are missing.'} This closes Chapter 2. Optional recorder repairs remain available before deciding.`,choices:[{id:'publish',label:'Publish the case. Make the hearing answer for it.'},{id:'deal',label:'Broker a truce through Bishop. Take $60 extra.'},{id:'protect',label:'Protect Ruiz’s identity. Keep the evidence for the hearing.'}]}
 };const spec=scripts[stage];host.open({title:node.title,eyebrow:`CHAPTER 2 · MOVE ${stage-7} / 6`,text:spec.text,actions:spec.choices.map(c=>({label:c.label,disabled:c.disabled,run:()=>{if(!chapterTwoChoice(host.s,stage,c.id))return;host.xp(stage===10?'Hustling':'Street Rep',stage===13?100:25);void host.save(false);host.open({title:stage===13?'CHAPTER 2 COMPLETE':node.title,eyebrow:'SOMEONE OWNS THE BLOCK',text:st.log.at(-1)!.text,actions:[{label:'Continue',run:()=>host.close()}]})}}))})}
export function recorderActions(host:Session,place:string):Action[]{const st=storyState(host.s);if(place!=='garage'||st.stage<8)return[];if(!st.side.recorder)return[{label:'SIDE QUEST · Keep the tape rolling',run:()=>{st.side.recorder=1;record(st,'Keep the tape rolling','Bring Ruiz one salvaged part to repair his recorder.');host.notify('Ruiz needs one salvaged part','Find parts at the salvage yard.');void host.save(false);host.location(place)}}];if(st.side.recorder===1)return[{label:'Repair Ruiz’s recorder · 1 salvaged part',disabled:!host.s.inventory.some(i=>i.id==='scrap'),run:()=>{if(st.side.recorder!==1||!removeItem(host.s,'scrap'))return;st.side.recorder=2;remember(st,'ruiz','Repaired the recorder that preserves his evidence.',20,10);if(st.stage>=13)addEvidence(st,'recording');host.s.cash+=30;host.xp('Hustling',40);record(st,'Keep the tape rolling','The repaired recorder can preserve the dispatcher’s voice.');host.notify('Recorder repaired','+$30 · Clear recordings preserved.','success');void host.save(false);host.location(place)}}];return[]}
