import {storyActions,storyGreeting,chapterThreeGreeting,storyPrice} from './story-panels';
import {storyState} from './story';
import {ITEMS,JOBS,PLACES,DRUGS,STREET_RANKS,streetRank,WEAPONS,levelFor,type Skill} from './data';
import {fresh,addItem,removeItem,award,saveGame,type Save} from './state';
import {BACKGROUNDS,type Background,type CharacterProfile} from './profile';
export type Toast={id:number;text:string;sub?:string;kind?:string};
export type Action={label:string;run:()=>void;disabled?:boolean};
export type Panel={title:string;eyebrow:string;text:string;actions:Action[]};
export class Session{
 s:Save=fresh();panel:Panel|null=null;toasts:Toast[]=[];onChange=()=>{};onSound=(kind:string)=>{};onWarp=(x:number,z:number)=>{};onFight=()=>{};onBasketball=()=>{};onDice=()=>{};onRace=(kind:'bike'|'street')=>{};onOutfit=()=>{};onWeapon=()=>{};onProfile=()=>{};onCloudSave=async(_save:Save)=>{};onVehicleBuy=(id:string)=>{};onVehicleRepair=()=>{};onGarage=(id:string,store:boolean)=>{};onHome=(inside:boolean)=>{};inside=false;dropped:{id:string;x:number;z:number}[]=[];savedAt=0;disposed=false;
 notify(text:string,sub?:string,kind='info'){this.toasts=[...this.toasts.slice(-3),{id:Date.now()+Math.random(),text,sub,kind}];this.onSound(kind);this.onChange();setTimeout(()=>{if(this.disposed)return;this.toasts.shift();this.onChange()},4500)}
 xp(skill:Skill,n:number){const personality=this.s.profile?.personality;if(skill==='Street Rep'&&personality==='charismatic')n=Math.round(n*1.2);if(skill==='Hustling'&&personality==='loyal')n=Math.round(n*1.1);const a=award(this.s,skill,n);if(a.after>a.before)this.notify(`${skill.toUpperCase()}  ${a.before} → ${a.after}`,a.unlock||'Your neighborhood story keeps growing.','level');else this.notify(`+${n} ${skill} XP`);this.onChange()}
 createProfile(profile:CharacterProfile){if(this.s.profile)return false;const name=profile.name.trim().replace(/\s+/g,' ').slice(0,18);if(name.length<2)return false;this.s.profile={...profile,name};const origin=BACKGROUNDS.find(x=>x.id===profile.background)! as Background;if(origin.cash)this.s.cash+=origin.cash;if(origin.item)addItem(this.s,origin.item,origin.qty);award(this.s,origin.skill,origin.xp);this.s.completed['origin:claimed']=1;this.onProfile();this.notify('YOUR NAME IS YOURS',`${name} · ${origin.label} · ${origin.effect}`,'success');void this.save(false);return true}
 raiseHeat(minimum:number,add=0){const quiet=this.s.profile?.personality==='quiet'?.25:0;this.s.heat=Math.min(5,Math.max(0,Math.max(minimum-quiet,this.s.heat+Math.max(0,add-quiet))))}
 open(panel:Panel){this.panel=panel;this.onChange()}
 close(){this.panel=null;this.onChange()}
 async save(show=true){try{await saveGame(this.s);this.savedAt=Date.now();void this.onCloudSave(structuredClone(this.s));if(show)this.notify('Progress saved','Your story stays with you.')}catch{this.notify('Could not save','Export your progress from Settings to keep a copy.')}this.onChange()}
 startJob(id:string){const j=JOBS.find(j=>j.id===id)!;if(this.s.active){this.notify('Finish your current Play first');return}if(levelFor(this.s.xp.Hustling)<j.requires)return;if(!addItem(this.s,'parcel')){this.notify('Your backpack is full');return}this.s.active=id;this.close();this.notify('NEW PLAY',j.name);void this.save(false)}
	 finishJob(place:string){const j=JOBS.find(j=>j.id===this.s.active);if(!j||j.target!==place)return false;removeItem(this.s,'parcel');this.s.active=null;this.s.completed[j.id]=(this.s.completed[j.id]||0)+1;this.s.cash+=j.reward;this.notify('PLAY COMPLETE',`${j.name}  ·  +$${j.reward}`,'success');this.xp(j.skill,j.xp);this.xp('Street Rep',j.rep);void this.save(false);return true}
	 rank(){return streetRank(this.s.xp.Hustling)}
	 supply(id:string){const d=DRUGS.find(d=>d.id===id);if(!d||this.rank()<d.rank)return;const cost=d.buy*3;if(this.s.cash<cost){this.notify(`You need $${cost}`);return}if(!addItem(this.s,id,3)){this.notify('Your backpack is full');return}this.s.cash-=cost;this.notify(`Picked up 3 × ${ITEMS[id].name}`,`−$${cost} · work a marked corner`);void this.save(false)}
	 sellDrug(id:string,corner:string){const d=DRUGS.find(d=>d.id===id);if(!d||!removeItem(this.s,id))return;const exposure=corner==='cornereast'?.25:0;this.s.dirtyCash=(this.s.dirtyCash||0)+d.sell;this.s.completed['street:sales']=(this.s.completed['street:sales']||0)+1;this.raiseHeat(d.heat+exposure);this.notify('STREET SALE',`${ITEMS[id].name} · +$${d.sell} hot cash`,'danger');this.xp('Hustling',18+d.rank*8);this.xp('Street Rep',5+d.rank*2);this.close();void this.save(false)}
	 robbery(kind:'home'|'bank'){const rank=this.rank(),gun=WEAPONS[this.s.weapon||'fists'].kind==='ranged';if(kind==='home'){if(rank<1||!this.s.inventory.some(i=>i.id==='lockpick'))return;if((this.s.completed['crime:homeReady']||0)>this.s.playtime){this.notify('The block is still watching','Come back later.');return}this.s.completed['crime:homeReady']=this.s.playtime+180;this.s.dirtyCash=(this.s.dirtyCash||0)+220;this.raiseHeat(3);this.xp('Hustling',90);this.xp('Street Rep',18);this.notify('HOME SCORE','+$220 hot cash · three-star response','danger')}else{if(rank<4||!gun)return;if((this.s.completed['crime:bankReady']||0)>this.s.playtime){this.notify('The bank is still locked down');return}this.s.completed['crime:bankReady']=this.s.playtime+600;this.s.dirtyCash=(this.s.dirtyCash||0)+2500;this.raiseHeat(5);this.xp('Hustling',300);this.xp('Street Rep',100);this.notify('BANK SCORE','+$2,500 hot cash · maximum response','danger')}this.close();void this.save(false)}
	 stashCash(){const amount=this.s.dirtyCash||0;if(this.s.heat>0){this.notify('Too hot to stash','Lose the cops first.');return}if(!amount)return;this.s.cash+=amount;this.s.dirtyCash=0;this.notify('MONEY STASHED',`$${amount} is clean and spendable.`,'success');void this.save(false)}
	 kingpinRun(){if(this.rank()<4||this.s.cash<1200)return;if((this.s.completed['crime:wholesaleReady']||0)>this.s.playtime){this.notify('The route is still burned');return}this.s.cash-=1200;this.s.dirtyCash=(this.s.dirtyCash||0)+2800;this.s.completed['crime:wholesaleReady']=this.s.playtime+480;this.s.completed['street:shipments']=(this.s.completed['street:shipments']||0)+1;this.raiseHeat(5);this.xp('Hustling',260);this.xp('Street Rep',90);this.notify('WHOLESALE RUN','-$1,200 fronted · $2,800 hot cash · maximum response','danger');this.close();void this.save(false)}
 price(id:string,place=''){const personality=this.s.profile?.personality==='calculating'?.93:1;return Math.max(1,Math.ceil((ITEMS[id]?.price||0)*storyPrice(this,id,place)*personality))}
 buy(id:string,place=''){const d=ITEMS[id],qty=id==='ammo9'?12:id==='shells'?6:id==='ammo556'?24:1,price=this.price(id,place)*qty;if(!d||d.price<=0)return;if(d.requiresCombat&&levelFor(this.s.xp.Combat)<d.requiresCombat){this.notify(`Combat level ${d.requiresCombat} required`,'Win court spars and challenge marked rivals.');return}if(this.s.cash<price){this.notify('Not enough cash');return}if(!addItem(this.s,id,qty)){this.notify('Your backpack is full');return}this.s.cash-=price;this.notify(`Bought ${qty>1?`${qty} × `:''}${d.name}`,`−$${price}`);void this.save(false)}
 sell(id:string){const d=ITEMS[id];if(!d||d.price<=0||id==='parcel'||id==='phone'||id===this.s.outfit||d.weapon===this.s.weapon){this.notify('Keep that one','Key items and equipped gear cannot be sold.');return}if(removeItem(this.s,id)){const value=Math.floor(d.price*.6);this.s.cash+=value;this.notify(`Sold ${d.name}`,`+$${value}`);this.xp('Hustling',5);void this.save(false)}}
 use(id:string){if(!this.s.inventory.some(i=>i.id===id))return;const d=ITEMS[id];if(d?.equip){this.s.outfit=id;this.onOutfit();this.notify(`Equipped ${d.name}`)}else if(d?.weapon){this.s.weapon=d.weapon;this.onWeapon();this.notify(`Equipped ${d.name}`,'Weapon damage and reach updated.')}else if(d?.heal||id==='water'){if(removeItem(this.s,id)){if(d.heal)this.s.health=Math.min(100,this.s.health+d.heal);else this.s.stamina=Math.min(100,this.s.stamina+20);this.notify(`Used ${d.name}`)}}else this.notify(d?.name||'Item',d?.desc);void this.save(false)}
 drop(id:string){if(['phone','parcel','jacket',this.s.outfit].includes(id)||ITEMS[id]?.weapon===this.s.weapon){this.notify('Keep that one','Equipped gear and key items stay with you.');return}if(removeItem(this.s,id)){this.dropped.push({id,x:this.s.x,z:this.s.z});this.notify(`Dropped ${ITEMS[id].name}`);this.onChange()}}
 bank(amount:number){if(amount>0){const n=Math.min(this.s.cash,amount);this.s.cash-=n;this.s.bank+=n;this.notify(`Banked $${n}`)}else{const n=Math.min(this.s.bank,-amount);this.s.bank-=n;this.s.cash+=n;this.notify(`Withdrew $${n}`)}void this.save(false);this.location('bank')}
	 location(id:string){const p=PLACES.find(p=>p.id===id);if(!p)return;if(this.finishJob(id))this.notify('Good looking out.','There’s always more work around the block.');
	 if(!this.s.discovered)this.s.discovered=[];if(!this.s.discovered.includes(id)){this.s.discovered.push(id);void this.save(false)}
 const actions:Action[]=storyActions(this,id);let text=p.hint;let title=p.name;
 if(id==='deli'){title='Malik';text='“Everybody starts somewhere. Take this parcel to Ms. June at Spin Cycle, and I’ll put something in your pocket.”'}
 if(id==='laundry'){title='Ms. June';text='“You new around here? Take care of your neighbors and they’ll take care of you.”'}
 if(id==='food'){title='Rosa';text='“A hot meal and honest work. What else do you need?”'}
 if(id==='clothes'){title='Nia';text='“Your name isn’t the only thing people remember. Make an impression.”'}
 if(id==='pawn'){title='Eli';text='“You bring me something worth buying, I’ll make you an offer.”'}
 if(id==='garage'){title='Ruiz';text='“I can sell you a runner. Or fix what you already have. Keep it clean around my shop.”'}
 for(const j of JOBS.filter(j=>j.giver===id&&this.s.discovered?.includes(j.giver)))actions.push({label:`${j.name}  ·  $${j.reward}${levelFor(this.s.xp.Hustling)<j.requires?` · Hustling ${j.requires}`:''}`,disabled:!!this.s.active||levelFor(this.s.xp.Hustling)<j.requires,run:()=>this.startJob(j.id)});
 const stock=id==='deli'?['water','snack','meal']:id==='food'?['meal','water']:id==='clothes'?['hoodie','cap']:id==='pawn'?['watch','tool','lockpick','bat','pipe','pistol','shotgun','carbine','ammo9','shells','ammo556']:id==='garage'?['tool']:[];
 for(const item of stock){const req=ITEMS[item].requiresCombat,locked=!!req&&levelFor(this.s.xp.Combat)<req,qty=item==='ammo9'?12:item==='shells'?6:item==='ammo556'?24:1;actions.push({label:`${locked?'LOCKED · ':''}Buy ${qty>1?`${qty} × `:''}${ITEMS[item].name}  ·  $${this.price(item,id)*qty}${req?` · Combat ${req}`:''}`,disabled:locked||this.s.inventory.some(i=>i.id===item&&!ITEMS[item].stack),run:()=>this.buy(item,id)})}
 if(id==='pawn')for(const item of this.s.inventory.filter(i=>ITEMS[i.id].price>0&&i.id!==this.s.outfit))actions.push({label:`Sell ${ITEMS[item.id].name}  ·  $${Math.floor(ITEMS[item.id].price*.6)}`,run:()=>{this.sell(item.id);this.location(id)}});
	 if(id==='bank'){text=`Cash $${this.s.cash}  ·  Bank $${this.s.bank}. Banked money is protected if you get caught.`;actions.push({label:'Deposit all cash',disabled:this.s.cash===0,run:()=>this.bank(this.s.cash)},{label:'Withdraw $50',disabled:this.s.bank===0,run:()=>this.bank(-50)},{label:'Withdraw all',disabled:this.s.bank===0,run:()=>this.bank(-this.s.bank)})}
	 if(id==='bank'){const locked=this.rank()<4||WEAPONS[this.s.weapon||'fists'].kind!=='ranged';actions.push({label:locked?'LOCKED · Bank robbery · Kingpin + firearm':'BANK ROBBERY · $2,500 hot cash · 5 stars',disabled:locked,run:()=>this.robbery('bank')})}
	 if(id==='plug'){title='Freight Contact';text=`Street rank: ${STREET_RANKS[this.rank()].name}. Buy three-unit packs, then work a marked corner.`;for(const d of DRUGS)actions.push({label:`${this.rank()<d.rank?'LOCKED · ':''}3 × ${ITEMS[d.id].name} · $${d.buy*3} · ${STREET_RANKS[d.rank].name}`,disabled:this.rank()<d.rank,run:()=>this.supply(d.id)});const wait=Math.ceil((this.s.completed['crime:wholesaleReady']||0)-this.s.playtime);actions.push({label:wait>0?`Wholesale route burned · ${wait}s`:this.rank()<4?'LOCKED · Kingpin wholesale route':'KINGPIN RUN · Front $1,200 · $2,800 hot',disabled:this.rank()<4||this.s.cash<1200||wait>0,run:()=>this.kingpinRun()})}
	 if(id==='cornerwest'||id==='cornereast'){title=id==='cornerwest'?'West Corner':'East Corner';text='Choose what to move. Every sale is deterministic: higher-value inventory creates stronger police exposure.';for(const item of this.s.inventory.filter(i=>ITEMS[i.id].drug))actions.push({label:`Sell ${ITEMS[item.id].name} · $${DRUGS.find(d=>d.id===item.id)?.sell} hot cash (${item.qty})`,run:()=>this.sellDrug(item.id,id)});if(!actions.length)actions.push({label:'No street inventory · find the Freight Contact',disabled:true,run:()=>{}})}
	 if(id==='rowhouse'){const locked=this.rank()<1||!this.s.inventory.some(i=>i.id==='lockpick'),remaining=Math.ceil((this.s.completed['crime:homeReady']||0)-this.s.playtime);title='Vacant Rowhouse';text='Bring lockpicks, commit to the score, then escape a three-star response and stash the money at home.';actions.push({label:remaining>0?`Block is hot · ${remaining}s`:locked?'LOCKED · Corner Seller + lockpicks':'HOME INVASION · $220 hot cash · 3 stars',disabled:locked||remaining>0,run:()=>this.robbery('home')})}
 if(id==='home'){if(this.s.heat>0){this.notify('Lose the Heat first','Keep police away from home.');return}text=this.inside?'A little space to call your own. Rest, change, stash your things.':'The light’s still on. Come upstairs, get some rest.';
 if(!this.inside)actions.push({label:'Go upstairs',run:()=>{this.inside=true;this.onHome(true);this.location('home')}});
 else{actions.push({label:`Stash hot cash · $${this.s.dirtyCash||0}`,disabled:!(this.s.dirtyCash||0),run:()=>{this.stashCash();this.location('home')}},{label:'Rest & save',run:()=>{this.s.health=100;this.s.stamina=100;this.notify('Rested','Health and stamina restored.');void this.save()}},{label:'Back to The Towers',run:()=>{this.inside=false;this.onHome(false);this.close()}});
 for(const item of this.s.inventory.filter(i=>!['phone','parcel',this.s.outfit].includes(i.id)&&ITEMS[i.id].weapon!==this.s.weapon))actions.push({label:`Store ${ITEMS[item.id].name}`,run:()=>{if(removeItem(this.s,item.id)){const old=this.s.storage.find(i=>i.id===item.id);if(old&&ITEMS[item.id].stack)old.qty++;else this.s.storage.push({id:item.id,qty:1})}this.location('home');void this.save(false)}});
 for(const item of this.s.storage)actions.push({label:`Take ${ITEMS[item.id].name} (${item.qty})`,run:()=>{if(addItem(this.s,item.id)){item.qty--;this.s.storage=this.s.storage.filter(i=>i.qty>0)}else this.notify('Your backpack is full');this.location('home');void this.save(false)}})}}
 if(id==='court'){title='Tower Court';text='Dre runs sparring rounds by the fence. The court is also open for skill-based shooting sessions.';actions.push({label:'PLAY BASKETBALL · 10-shot run',run:()=>{this.close();this.onBasketball()}},{label:'Spar with Dre  ·  $30 prize',disabled:this.s.health<25,run:()=>{this.close();this.onFight()}})}
 if(id==='garage'){for(const owned of this.s.owned){const stored=!!this.s.completed['garaged:'+owned];actions.push({label:`${stored?'Retrieve':'Store'} ${owned.startsWith('bike')?'bicycle':'car'}`,run:()=>{this.onGarage(owned,!stored);this.location('garage');void this.save(false)}})}if(!this.s.owned.includes('bike1'))actions.push({label:'Buy Mercer BMX  ·  $80',run:()=>{if(this.s.cash<80){this.notify('You need $80');return}this.s.cash-=80;this.s.owned.push('bike1');this.onVehicleBuy('bike1');this.notify('YOUR FIRST RIDE','Mercer BMX is yours.','success');this.location('garage');void this.save(false)}});if(!this.s.owned.includes('sedan1'))actions.push({label:'Buy 1998 Regent  ·  $650',run:()=>{if(this.s.cash<650){this.notify('You need $650');return}this.s.cash-=650;this.s.owned.push('sedan1');this.onVehicleBuy('sedan1');this.notify('Regent purchased','Find it outside Ruiz Auto.','success');this.location('garage');void this.save(false)}});const repairPrice=storyState(this.s).flags.some(f=>['route_silence','source_protected'].includes(f))?5:10;actions.push({label:`Repair owned vehicles  ·  $${repairPrice}`,disabled:!this.s.owned.length,run:()=>{if(this.s.cash<repairPrice){this.notify(`You need $${repairPrice}`);return}this.s.cash-=repairPrice;this.onVehicleRepair();this.notify('All owned rides repaired');void this.save(false)}})}
 if(id==='salvage'){const last=this.s.completed.salvageTime||0;const remaining=Math.ceil(90-(this.s.playtime-last));text='There’s money in what people leave behind. Search for usable parts.';actions.push({label:last&&remaining>0?`Search again in ${remaining}s`:'Search for salvage',disabled:!!last&&remaining>0,run:()=>{if(!addItem(this.s,'scrap')){this.notify('Your backpack is full');return}this.s.completed.salvageTime=this.s.playtime;this.xp('Hustling',15);this.notify('Found salvaged parts','Sell them at Goldline Pawn.');this.close();void this.save(false)}})}
 if(id==='garage')actions.push({label:'BIKE RACE · Mercer circuit',disabled:!this.s.owned.some(x=>x.startsWith('bike')),run:()=>{this.close();this.onRace('bike')}},{label:'STREET RACE · District 09 loop',disabled:!this.s.owned.some(x=>x.startsWith('sedan')),run:()=>{this.close();this.onRace('street')}});
 if(id==='dice'){title='Alley Dice';text='Pick the call before the eight-second clock expires. Stakes are paid from clean cash.';actions.push({label:'PLAY DICE · choose your stake',run:()=>{this.close();this.onDice()}})}
 text=storyGreeting(this,id)||chapterThreeGreeting(this,id)||text;this.open({title,eyebrow:id==='home'?'HOME • THE TOWERS':p.name,text,actions});
 }
	 defeat(arrest=false){const loss=Math.min(this.s.cash,arrest?40:15),hot=this.s.dirtyCash||0;this.s.cash-=loss;this.s.dirtyCash=arrest?0:Math.floor(hot*.5);this.s.health=100;this.s.stamina=100;this.s.heat=0;this.inside=false;this.onHome(false);this.onWarp(-8,-36);this.close();this.notify(arrest?'BUSTED':'BACK ON YOUR FEET',`Lost $${loss} cash${hot?` and ${arrest?'all':'half'} hot money`:''}. Banked money is safe.`, 'danger');void this.save(false)}
}
