import {newStory,validStory,type StoryState} from './story';
import {SKILLS,type Skill,levelFor,UNLOCKS,ITEMS,JOBS,PLACES,VEHICLE_DEFS,WEAPONS,type Weapon} from './data';
import {DEFAULT_PROFILE,validProfile,type CharacterProfile} from './profile';
export type Save={profile?:CharacterProfile;path?:'story'|'sandbox';tutorial?:{step:number;complete:boolean};story?:StoryState;discovered?:string[];version:1;cash:number;dirtyCash?:number;bank:number;health:number;stamina:number;x:number;z:number;xp:Record<Skill,number>;inventory:{id:string;qty:number}[];storage:{id:string;qty:number}[];completed:Record<string,number>;active:string|null;owned:string[];vehicles:Record<string,{x:number;z:number;yaw:number;condition:number}>;outfit:string;weapon?:Weapon;heat:number;playtime:number;settings:{sound:boolean;quality:string;sensitivity:number};intro:boolean};
export const fresh=():Save=>({story:newStory(),discovered:[],version:1,cash:40,dirtyCash:0,bank:0,health:100,stamina:100,x:-15,z:-35,xp:Object.fromEntries(SKILLS.map(s=>[s,0])) as Record<Skill,number>,inventory:[{id:'phone',qty:1},{id:'jacket',qty:1}],storage:[],completed:{},active:null,owned:[],vehicles:{},outfit:'jacket',weapon:'fists',heat:0,playtime:0,settings:{sound:true,quality:'auto',sensitivity:1},intro:false});
export function addItem(s:Save,id:string,qty=1){const def=ITEMS[id];if(!def||qty<1)return false;const stack=s.inventory.find(i=>i.id===id);if(def.stack&&stack){stack.qty+=qty;return true}if(s.inventory.length+(def.stack?1:qty)>24)return false;for(let i=0;i<(def.stack?1:qty);i++)s.inventory.push({id,qty:def.stack?qty:1});return true}
export function removeItem(s:Save,id:string,qty=1){const i=s.inventory.findIndex(i=>i.id===id);if(i<0||s.inventory[i].qty<qty)return false;s.inventory[i].qty-=qty;if(!s.inventory[i].qty)s.inventory.splice(i,1);return true}
export function award(s:Save,skill:Skill,xp:number){const before=levelFor(s.xp[skill]);s.xp[skill]+=xp;const after=levelFor(s.xp[skill]);return {skill,xp,before,after,unlock:UNLOCKS[skill]?.[after]}}
let dbPromise:Promise<IDBDatabase>|null=null;
function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('hoodscape-saint-mercer',1);r.onupgradeneeded=()=>r.result.createObjectStore('saves');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise}
export function validSave(raw:unknown):raw is Save{
 if(!raw||typeof raw!=='object')return false;const s=raw as Save;
	 const finite=(n:unknown,min=0,max=Number.MAX_SAFE_INTEGER)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
	 const bag=(v:unknown)=>Array.isArray(v)&&v.every(i=>i&&!!ITEMS[i.id]&&Number.isInteger(i.qty)&&i.qty>0&&i.qty<1000000&&(ITEMS[i.id].stack||i.qty===1));
	 if(s.dirtyCash!==undefined&&!finite(s.dirtyCash))return false;if(s.profile!==undefined&&!validProfile(s.profile))return false;if(s.path!==undefined&&!['story','sandbox'].includes(s.path))return false;if(s.tutorial!==undefined&&(!s.tutorial||!Number.isInteger(s.tutorial.step)||s.tutorial.step<0||s.tutorial.step>8||typeof s.tutorial.complete!=='boolean'))return false;if(s.discovered!==undefined&&(!Array.isArray(s.discovered)||s.discovered.some(id=>typeof id!=='string'||!PLACES.some(p=>p.id===id))))return false;
 return (s.story===undefined||validStory(s.story))&&s.version===1&&finite(s.cash)&&finite(s.bank)&&finite(s.x,-66.5,66.5)&&finite(s.z,-71.5,71.5)&&finite(s.health,0,100)&&finite(s.stamina,0,100)&&finite(s.heat,0,5)&&finite(s.playtime)&&SKILLS.every(k=>finite(s.xp?.[k]))&&bag(s.inventory)&&s.inventory.length<=24&&bag(s.storage)&&Array.isArray(s.owned)&&s.owned.every(id=>VEHICLE_DEFS.some(v=>v.id===id))&&!!s.completed&&Object.values(s.completed).every(n=>finite(n))&&(s.active===null||JOBS.some(j=>j.id===s.active))&&(!s.active||s.inventory.some(i=>i.id==='parcel'))&&!!ITEMS[s.outfit]?.equip&&(s.weapon===undefined||!!WEAPONS[s.weapon]&&(s.weapon==='fists'||s.inventory.some(i=>ITEMS[i.id]?.weapon===s.weapon)))&&!!s.vehicles&&Object.entries(s.vehicles).every(([id,v])=>VEHICLE_DEFS.some(d=>d.id===id)&&finite(v.x,-66,66)&&finite(v.z,-71,71)&&finite(v.yaw,-100000,100000)&&finite(v.condition,0,100))&&!!s.settings&&typeof s.settings.sound==='boolean'&&['auto','high','low'].includes(s.settings.quality)&&finite(s.settings.sensitivity,.3,2.5);
}
export async function loadSave(){const d=await db();return new Promise<Save|null>((resolve,reject)=>{const tx=d.transaction('saves','readonly');const r=tx.objectStore('saves').get('current');r.onsuccess=()=>{if(validSave(r.result)){resolve(migrateSave(r.result));return}const b=tx.objectStore('saves').get('backup');b.onsuccess=()=>resolve(validSave(b.result)?migrateSave(b.result):null);b.onerror=()=>reject(b.error)};r.onerror=()=>reject(r.error)})}
export async function saveGame(s:Save){const d=await db();const snapshot=structuredClone(s);return new Promise<void>((resolve,reject)=>{const tx=d.transaction('saves','readwrite');const st=tx.objectStore('saves');const old=st.get('current');old.onsuccess=()=>{if(validSave(old.result))st.put(old.result,'backup');st.put(snapshot,'current')};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}

export function migrateSave(s:Save):Save{return {...fresh(),...s,...(s.profile?{profile:{...DEFAULT_PROFILE,...s.profile,face:s.profile.face??DEFAULT_PROFILE.face,head:s.profile.head??DEFAULT_PROFILE.head,body:s.profile.body??DEFAULT_PROFILE.body}}:{}),discovered:s.discovered??PLACES.map(p=>p.id),dirtyCash:s.dirtyCash??0,weapon:s.weapon??'fists',story:s.story??newStory()}}
