import {chapterTwoPanel,recorderActions} from './chapter-two';
import {chapterThreePanel,chapterThreeActions} from './chapter-three';
import {chapterFourPanel,chapterFourActions} from './chapter-four';
import type {Session,Action} from './session';
import {CHAPTER_ONE,STORY_MOVES,chapterChoice,storyState,relaySwitch,remember,addEvidence,record} from './story';
import {removeItem} from './state';
export function storyPanel(host:Session){const st=storyState(host.s),stage=st.stage;if(stage>=19){chapterFourPanel(host);return;}if(stage>=14){chapterThreePanel(host);return;}if(stage>=8){chapterTwoPanel(host);return;}const node=CHAPTER_ONE[stage];let title=node.title,text='',choices:{id:string;label:string}[]=[];
 switch(stage){
 case 0:title='Malik · renewal notices';text='“Same company bought three buildings this week. Now June’s getting calls about a relocation agreement. They say it’s voluntary. Funny how the lights went out the day she said no.”';choices=[{id:'help',label:'I’ll check on June.'},{id:'business',label:'I can look into it. Pay me an advance.'}];break;
 case 1:title='June · a familiar song';text='“They want me to leave a place I’ve lived my whole life. The man on the phone hummed a tune from my childhood. Four notes. Nobody else remembers it. Does that sound foolish to you?”';choices=[{id:'believe',label:'I believe you. Tell me what you remember.'},{id:'dismiss',label:'It could just be an old jingle.'}];break;
 case 2:title='Ruiz · dead air';text='“That tune came out of my radio with the battery disconnected. Say that out loud and you sound crazy. The street relay is faulty too. We can check something real before chasing ghosts.”';choices=[{id:'investigate',label:'Show me how to reset the relay.'}];break;
 case 3:title='Street relay';text=st.relay===0?'Ruiz’s safe reset: GROUND → BYPASS → RELAY. Restore power, then inspect the maintenance log.':st.relay===1?'Ground isolated. The bypass is next.':'Bypass stable. Reconnect the relay.';break;
 case 4:title='Contractor’s cabinet';text='A locked service screen wakes when you enter Ruiz’s relay code. Inside: a disposal tray, $60 in petty cash, and relocation payments to both the protection fund and its supposed victims. You have time to copy the records or grab the cash before disposal.';choices=[{id:'copy',label:'Copy the ledger. Leave the money.'},{id:'cash',label:'Take the $60. Let the records go.'}];break;
 case 5:title='Bishop · friendly warning';text='“I hear you’re asking about renewal money. Malik sells groceries. He doesn’t understand who keeps those trucks arriving. Here’s ninety. Bring your findings to me, and nobody has to make a mistake.”';choices=[{id:'refuse',label:'Keep it. You don’t own my questions.'},{id:'accept',label:'I’ll take the advance. We’ll talk.'}];break;
 case 6:title='Dre · someone in your corner';text='“Bishop’s watching you. He calls it a favor until it becomes a debt. Tell me what happened. I can stand beside you, but I need to know what I’m standing in.”';choices=[{id:'honest',label:'Tell Dre everything about the offer.'},{id:'private',label:'I’ve got it handled. Leave it with me.'}];break;
 case 7:title='Malik · who gets the truth?';text=`“You’ve seen enough to know this isn’t just one bad landlord. Who are we trusting with it?” ${st.evidence.includes('ledger')?'You kept the ledger. You have proof.':'The ledger is gone. You have the signal log and what you remember.'} ${st.side.dre===2?'Dre has offered to back you.':''} This decision closes Chapter 1. You can finish optional favors before deciding.`;choices=[{id:'neighbors',label:'Share it with the tenants. Protect June.'},{id:'bishop',label:'Give Bishop the findings. Take his access.'},{id:'bury',label:'Keep it quiet. We’re not ready.'}];break;
 }
 const actions:Action[]=choices.map(c=>({label:c.label,run:()=>{const result=chapterChoice(host.s,stage,c.id);if(!result.ok)return;host.xp('Street Rep',result.xp);void host.save(false);host.open({title:stage===7?'CHAPTER 1 COMPLETE':title,eyebrow:'EVERYBODY STARTS SOMEWHERE',text:result.text,actions:[{label:stage===7?'Back to the neighborhood':'Continue',run:()=>host.close()}]})}}));
 if(stage===3)for(const key of ['ground','bypass','relay'])actions.push({label:key.toUpperCase(),run:()=>{if(st.stage!==3)return;const result=relaySwitch(host.s,key);if(result.done){host.xp('Hustling',55);host.open({title:'Power restored',eyebrow:'MAINTENANCE LOG · 03:17',text:result.text,actions:[{label:'Head to the salvage yard',run:()=>host.close()}]})}else{storyPanel(host);if(!result.ok)host.notify('Breaker reset',result.text)}void host.save(false)}});
 host.open({title,eyebrow:`CHAPTER 1 · MOVE ${stage+1} / 8`,text,actions});
}
export function storyActions(host:Session,place:string):Action[]{const st=storyState(host.s),actions:Action[]=[...chapterFourActions(host,place),...chapterThreeActions(host,place),...recorderActions(host,place)];if(STORY_MOVES[st.stage]?.place===place)actions.push({label:`STORY · ${STORY_MOVES[st.stage].title}`,run:()=>storyPanel(host)});
 const refresh=()=>{void host.save(false);host.location(place)};
 if(place==='laundry'){
 if(!st.side.keepsake)actions.push({label:'SIDE QUEST · A place in the picture',run:()=>host.open({title:'June · a place in the picture',eyebrow:'OPTIONAL FAVOR',text:'“Eli’s holding an envelope from my old storage locker. Nothing valuable. Just a photograph. Would you ask him for it? I don’t like going alone anymore.”',actions:[{label:'I’ll bring it back.',run:()=>{if(st.side.keepsake)return;st.side.keepsake=1;record(st,'A place in the picture','Promised to retrieve June’s envelope from Goldline Pawn.');refresh()}}]})});
 if(st.side.keepsake===2)actions.push({label:'Return June’s envelope',run:()=>{if(st.side.keepsake!==2)return;st.side.keepsake=3;remember(st,'june','Returned her photograph without asking for payment.',25,5);addEvidence(st,'envelope');host.s.cash+=25;host.xp('Street Rep',30);record(st,'A place in the picture','June recognized someone missing from the photograph. She trusts you with memories she will not share with strangers.');host.open({title:'June remembers',eyebrow:'SIDE QUEST COMPLETE · +$25',text:'“There should be somebody between us.” June traces a white space in the photograph. “I remember holding his hand.” She gives you a copy, then presses $25 into your palm.',actions:[{label:'Keep the photograph safe.',run:()=>host.close()}]});void host.save(false)}});
 }
 if(place==='pawn'&&st.side.keepsake===1)actions.push({label:'Ask Eli for June’s envelope',run:()=>{if(st.side.keepsake!==1)return;st.side.keepsake=2;host.notify('Envelope recovered','Return it to June.');refresh()}});
 if(place==='court'){
 if(!st.side.dre)actions.push({label:'SIDE QUEST · Show up for somebody',run:()=>{st.side.dre=1;st.side.dreTarget=(host.s.completed.spar||0)+1;record(st,'Show up for somebody','Promised Dre a fresh training session. Win a spar, then check in.');host.notify('Dre needs a training partner','Win a new spar, then talk to him.');refresh()}});
 if(st.side.dre===1&&(host.s.completed.spar||0)>=st.side.dreTarget)actions.push({label:'Check in with Dre after training',run:()=>{if(st.side.dre!==1)return;st.side.dre=2;remember(st,'dre','Showed up for a promised training session.',25,20);host.s.cash+=40;host.xp('Street Rep',25);record(st,'Show up for somebody','Dre offered to stand with you and accompany June to the tenant meeting.');host.notify('DRE WILL VOUCH FOR YOU','+$40 · A promise kept.','success');refresh()}});
 }
 if(place==='food'){
 if(!st.side.rosa)actions.push({label:'SIDE QUEST · Water before business',run:()=>{st.side.rosa=1;record(st,'Water before business','Rosa needs one cold water while keeping the kitchen running.');host.notify('Bring Rosa one cold water');refresh()}});
 if(st.side.rosa===1)actions.push({label:'Give Rosa a cold water',disabled:!host.s.inventory.some(i=>i.id==='water'),run:()=>{if(st.side.rosa!==1||!removeItem(host.s,'water'))return;st.side.rosa=2;remember(st,'rosa','Helped her before asking for business.',25,5);record(st,'Water before business','Rosa now offers 15% off meals and drinks at Sunday’s Kitchen.');host.xp('Street Rep',20);host.notify('ROSA LOOKS AFTER HER PEOPLE','15% off at Sunday’s Kitchen.','success');refresh()}});
 }
 if(place==='bishop'&&st.flags.includes('bishop_collecting'))actions.push({label:'Repay Bishop’s advance · $90',disabled:host.s.cash<90,run:()=>{if(!st.flags.includes('bishop_collecting')||host.s.cash<90)return;host.s.cash-=90;st.flags=st.flags.filter(f=>!['bishop_collecting','bishop_debt'].includes(f));remember(st,'bishop','Repaid the advance instead of hiding.',5,20,-15);record(st,'Debt settled','Bishop stops following you. He still remembers being refused.');host.notify('Debt settled','Bishop backs off.');refresh()}});
 return actions;
}
export function storyGreeting(host:Session,place:string):string|undefined{const st=storyState(host.s);if(place==='bishop'&&st.flags.includes('shipment_truce'))return '“A truce, paid deliveries, and no outstanding advance. That’s what my word bought you.”';if(place==='deli'&&st.flags.includes('public_case'))return '“They’re hearing our case. You’re welcome at this counter.”';if(place==='food'&&st.flags.includes('community_meals'))return '“The meal table is still running. You helped make that happen.”';if(place==='garage'&&st.flags.includes('source_protected'))return '“You kept my name out of it. Five-dollar repairs. Anytime.”';if(place==='bishop')return st.flags.includes('bishop_collecting')?'“Ninety dollars. Then you can go back to pretending we never met.”':st.relationships.bishop.resentment>=25?'“You made your choice. Remember that when the block changes.”':st.flags.includes('route_bishop')?'“You kept your word. Next time, I’ll introduce you to somebody who signs the checks.”':'“Word travels fast around The Towers. Be careful what you let people hear.”';if(place==='deli'&&st.flags.includes('route_bishop'))return '“Bishop got his information. You can still shop here. Just don’t ask for the neighbor price.”';if(place==='deli'&&st.flags.includes('route_neighbors'))return '“Ten percent off. Anybody who stands with this block eats a little cheaper.”'; if(place==='laundry'&&st.side.keepsake===3)return '“I put your copy somewhere safe. That missing boy... I think he knew your name.”';
 if(place==='laundry'&&st.stage>=19&&st.stage<24)return '“They keep editing him out. His name was Theo. The bus driver asks who I’m waving at now.”';if(place==='laundry'&&st.relationships.june.trust<=-15)return '“I remember what you said about my memory. What do you need?”';if(place==='court'&&st.side.dre===2)return '“You showed up. If June needs somebody at that meeting, I’m there.”';if(place==='food'&&st.side.rosa===2)return '“You brought me water when I needed it. Your food’s fifteen percent off.”';if(place==='garage'&&st.flags.includes('route_silence'))return '“We keep the relay fixed and our mouths shut, for now. Half-price repairs. You earned that much.”';}
export function chapterThreeGreeting(host:Session,place:string):string|undefined{const st=storyState(host.s);if(place==='meeting'&&st.flags.includes('attendance_exposed'))return '“The attendance list is in every tenant’s phone now. Vale can call it disruption; nobody can call it imaginary.”';if(place==='meeting'&&st.flags.includes('vale_role'))return '“That badge opens doors. It also tells people who signed for them.”';if(place==='meeting'&&st.flags.includes('tenant_network'))return '“The independent line is live. The noticeboard is no longer the only way we find each other.”';if(place==='clothes'&&st.flags.includes('merchant_saved'))return '“The storefront is still mine. That means more than a nicer sign.”';if(place==='bank'&&st.flags.includes('duplicate_records'))return '“The names do not match the lives attached to them. Ruiz says that is the point.”';}
export function storyPrice(host:Session,id:string,place:string){const st=storyState(host.s);let multiplier=1;if(place==='food'&&st.side.rosa===2)multiplier=.85;if(place==='deli'&&st.flags.includes('route_neighbors'))multiplier=.9;if(place==='deli'&&st.flags.includes('route_bishop'))multiplier=1.15;if(place==='deli'&&st.flags.includes('market_priority'))multiplier*=.9;if(place==='food'&&st.flags.includes('community_meals'))multiplier*=.9;return multiplier}
