import type {Save} from './state';
export const CONTACTS={malik:'Malik',june:'Ms. June',ruiz:'Ruiz',dre:'Dre',rosa:'Rosa',bishop:'Bishop'} as const;
export type Contact=keyof typeof CONTACTS;
export type Bond={trust:number;respect:number;resentment:number;memories:string[]};
export type StoryState={revision:1;stage:number;choices:Record<string,string>;flags:string[];evidence:string[];relationships:Record<Contact,Bond>;side:Record<string,number>;relay:number;log:{title:string;text:string}[]};
export const newStory=():StoryState=>({revision:1,stage:0,choices:{},flags:[],evidence:[],relationships:Object.keys(CONTACTS).reduce((r,k)=>{r[k as Contact]={trust:0,respect:0,resentment:0,memories:[]};return r},{} as Record<Contact,Bond>),side:{},relay:0,log:[]});
export function storyState(s:Save){return s.story??(s.story=newStory())}
export const EVIDENCE:Record<string,{title:string;text:string}>={song:{title:'A song without a station',text:'June remembers a four-note radio jingle from a childhood evacuation. Ruiz heard the same notes on a disconnected workshop radio.'},signal:{title:'The 03:17 signal',text:'The street relay records a service broadcast at 03:17 every morning. There is no receiving address, only a repeated instruction: MAINTAIN BASELINE.'},ledger:{title:'A copied relocation ledger',text:'A Mercer Civic Renewal contractor paid both a neighborhood protection fund and the company buying its victims’ buildings. One account is labelled ASSEMBLY / COMMUNITY STABILITY.'},envelope:{title:'The empty photograph',text:'June’s old envelope holds a school photograph with a clean white space between two children. She remembers someone standing there. On its reverse: Saint Mercer Evacuation, 1998.'},hearing_notes:{title:'A hearing in three voices',text:'The public hearing record captures tenants describing the same pressure campaign in their own words. Their testimony gives the neighborhood a shared account before the paperwork can be changed.'},attendance:{title:'Manufactured attendance',text:'The Saint Mercer Initiative’s sign-in sheet repeats tenant signatures, times, and handwriting patterns. Several people listed as present were working across town.'},permit_order:{title:'A permit with a hidden price',text:'Nia’s permit offer grants a storefront only if the Assembly can claim the back room for “community coordination.” The approval is a property transfer disguised as help.'},citizen_files:{title:'Duplicate citizen records',text:'The licensing archive lists the same employees under different names and start dates. The duplicates move people between properties whenever the Initiative needs a clean paper trail.'},
missing_person:{title:'A neighbor nobody else remembers',text:'There is no Theo Wells in the Initiative’s archive. The rent fund, the mailbox, and the roster all end in a clean, deliberate gap. What remains is June’s memory and whatever paper escaped the edit.'},
envelope_scan:{title:'The photograph that survived',text:'June’s envelope photograph from the 1998 evacuation still shows Theo’s face beside hers. The record change never touched the paper copy. It is physical proof that he existed.'},
theo_recording:{title:'Subject 12, logged like inventory',text:'Ruiz’s repaired recorder preserved a maintenance channel: “Subject 12 relocated, 1998. Effects disposition pending.” A child was picked up by Initiative transport and entered into an effects ledger.'},
resident_file:{title:'Theo Wells, resident file',text:'The Initiative’s personnel archive still lists Theo Wells: enrolled at age six, relocated 1998, flagged “contagious” for his effect on surrounding subjects. The file includes his photograph.'}};
export const CHAPTER_ONE=[
 {title:'People know your face',place:'deli',objective:'Ask Malik about the renewal notices.'},
 {title:'A familiar song',place:'laundry',objective:'Talk to June about the notice on her door.'},
 {title:'Dead air',place:'garage',objective:'Ask Ruiz about June’s radio jingle.'},
 {title:'Keep the lights on',place:'relay',objective:'Restore the street relay beside Mercer ATM.'},
 {title:'Paper trail',place:'salvage',objective:'Inspect the contractor’s cabinet at the salvage yard.'},
 {title:'Friendly warning',place:'bishop',objective:'Meet Bishop beside Tower Court.'},
 {title:'Someone in your corner',place:'court',objective:'Ask Dre what he knows about Bishop.'},
 {title:'Who gets the truth?',place:'deli',objective:'Return to Malik and decide who gets the evidence.'}
];
export const SIDE_QUESTS=[{id:'keepsake',title:'A place in the picture',giver:'laundry',description:'Help June recover an old envelope from Goldline Pawn. Eli will release it as a favor if you ask.',steps:['Ask June about her lost keepsake.','Ask Eli at Goldline Pawn for June’s envelope.','Return the envelope to June.','Complete · June remembers your kindness.']},{id:'dre',title:'Show up for somebody',giver:'court',description:'Dre wants a reliable training partner. Agree to a session, win a new spar, and check back in.',steps:['Ask Dre if he needs a training partner.','Win a spar after accepting, then talk to Dre.','Complete · Dre will vouch for you.']},{id:'rosa',title:'Water before business',giver:'food',description:'Rosa is keeping the kitchen open through the outage. Bring her one cold water.',steps:['Ask Rosa how the kitchen is holding up.','Bring Rosa one cold water.','Complete · Sunday’s gives you a 15% food discount.']}];
export function remember(st:StoryState,id:Contact,text:string,trust=0,respect=0,resentment=0){const r=st.relationships[id];r.trust=Math.max(-100,Math.min(100,r.trust+trust));r.respect=Math.max(-100,Math.min(100,r.respect+respect));r.resentment=Math.max(0,Math.min(100,r.resentment+resentment));if(!r.memories.includes(text))r.memories.push(text)}
export function record(st:StoryState,title:string,text:string){st.log.push({title,text});if(st.log.length>60)st.log.shift()}
export function addEvidence(st:StoryState,id:string){if(!st.evidence.includes(id))st.evidence.push(id)}
export function bondLabel(b:Bond){if(b.resentment>=25)return 'Resentful';if(b.trust<=-15)return 'Distrustful';if(b.trust>=35)return 'Trusted';if(b.trust>=15)return 'Warming up';if(b.respect>=15)return 'Respected';return 'Getting acquainted'}
export function chapterChoice(s:Save,stage:number,choice:string):{ok:boolean;text:string;cash:number;xp:number}{const st=storyState(s),fail={ok:false,text:'That conversation has moved on.',cash:0,xp:0};if(st.stage!==stage||st.choices[String(stage)])return fail;let text='',cash=0,xp=15;
 const valid=[['help','business'],['believe','dismiss'],['investigate'],[],['copy','cash'],['refuse','accept'],['honest','private'],['neighbors','bishop','bury']];if(!valid[stage]?.includes(choice))return fail;
 switch(stage){
 case 0:if(choice==='help'){remember(st,'malik','Offered to help with the renewal notices.',15,5);text='Malik gives you June’s notice. “Don’t let anybody rush her into signing.”'}else{remember(st,'malik','Asked what the neighborhood’s trouble would pay.',-5,5);cash=15;text='Malik pays a $15 advance. “Fine. But June is a person, not a delivery address.”'}break;
 case 1:if(choice==='believe'){remember(st,'june','Listened when nobody else believed her.',20);addEvidence(st,'song');text='June hums four notes. “I heard that on the evacuation bus. Ruiz says his radio played it with the battery out.”'}else{remember(st,'june','Dismissed her memory as a mistake.',-15,0,10);text='June folds the notice away. “Ask Ruiz about the radio, then. Maybe you’ll believe a machine.”'}break;
 case 2:remember(st,'ruiz','Offered to investigate the failing street relay.',10,5);text='Ruiz draws a safe reset sequence: GROUND → BYPASS → RELAY. “The box is beside the ATM. Read its service log after it comes back.”';break;
 case 4:if(choice==='copy'){addEvidence(st,'ledger');remember(st,'ruiz','Preserved the contractor’s payment records.',10,10);text='You copy the ledger and leave the originals. Two opposed groups receive payments from the same contractor. Bishop’s name appears beside a meeting at Tower Court.'}else{cash=60;st.flags.push('ledger_lost');remember(st,'ruiz','Took the cabinet’s cash and left the records behind.',-10,0,10);text='You take $60 from the cabinet. Its disposal cycle destroys the papers. You catch Bishop’s name and a Tower Court meeting before the feed closes.'}break;
 case 5:if(choice==='refuse'){remember(st,'bishop','Rejected his advance in front of the court.',-20,15,25);text='Bishop pockets the money. “Everybody on this block pays somebody. You’ll learn.” He watches you leave.'}else{cash=90;st.flags.push('bishop_debt');remember(st,'bishop','Accepted his $90 advance and promised discretion.',15,5);text='Bishop hands you $90. “It’s an introduction, not a gift. Bring anything interesting to me before Malik.”'}break;
 case 6:if(choice==='honest'){remember(st,'dre','Told him the truth about Bishop’s offer.',20,10);if(st.flags.includes('bishop_debt'))text='Dre exhales. “You took his money? Then you owe him a decision. I’m glad you told me.”';else text='Dre nods. “He tried that with me. Decide who gets your information before he decides for you.”'}else{remember(st,'dre','Kept Bishop’s offer private.',-10,0,10);text='Dre stops smiling. “You don’t owe me every detail. But don’t ask me to back a story you won’t tell me.”'}break;
 case 7:{xp=90;cash=100;const proof=st.evidence.includes('ledger'),ally=st.side.dre===2;
 if(choice==='neighbors'){st.flags.push('route_neighbors');remember(st,'malik','Shared the investigation with the neighborhood.',25,15);remember(st,'june','Put her safety ahead of Bishop’s offer.',15);remember(st,'bishop','Brought the information to Malik instead.',-15,0,25);if(st.flags.includes('bishop_debt')){st.flags.push('bishop_collecting');text='Bishop wants his $90 back. '}text+=proof?'Malik copies the ledger for the tenants. His shop now gives you 10% off.':'Without a ledger, the tenants have testimony instead of proof. Malik still gives you 10% off.';if(ally)text+=' Dre agrees to accompany June to the meeting.'}
 if(choice==='bishop'){st.flags.push('route_bishop');remember(st,'bishop','Honored the agreement and brought him the evidence.',30,15);remember(st,'malik','Handed the investigation to Bishop.',-25,0,25);remember(st,'june','Put Bishop in charge of her story.',-15,0,15);cash+=proof?80:30;text='Bishop pays for your findings and clears the advance. Malik hears about it; his shop charges you 15% more. Bishop promises access to whoever signs the renewal orders.';st.flags=st.flags.filter(f=>f!=='bishop_debt')}
 if(choice==='bury'){st.flags.push('route_silence');remember(st,'malik','Asked him to keep the findings out of circulation.',-10);remember(st,'june','Kept the investigation quiet.',-5);text='Malik locks the file away. Nobody gets a public warning. Ruiz offers half-price repairs because you fixed the relay. The pressure on the neighborhood continues.'}
 st.flags.push('chapter_one_complete');text+=' Later, Ruiz calls: “That contractor account? Somebody just renamed it THE ASSEMBLY.”';break;
 }}
 st.choices[String(stage)]=choice;st.stage++;s.cash+=cash;record(st,CHAPTER_ONE[stage].title,text);return{ok:true,text,cash,xp};
}
export function relaySwitch(s:Save,key:string){const st=storyState(s);if(st.stage!==3)return{ok:false,done:false,text:'The relay is already online.'};const sequence=['ground','bypass','relay'];if(key!==sequence[st.relay]){st.relay=0;return{ok:false,done:false,text:'The breaker trips safely. Start again: ground, bypass, relay.'}}st.relay++;if(st.relay<3)return{ok:true,done:false,text:st.relay===1?'Ground isolated. Select BYPASS.':'Bypass stable. Select RELAY.'};st.stage=4;st.choices['3']='restored';st.flags.push('relay_restored');addEvidence(st,'signal');remember(st,'ruiz','Restored the street relay instead of walking away.',15,15);record(st,'Keep the lights on','Power restored. The maintenance log points to a contractor’s cabinet in the salvage yard. Its 03:17 broadcast says MAINTAIN BASELINE.');return{ok:true,done:true,text:'The relay hums back to life. Its log points to the salvage yard. A nightly transmission reads: MAINTAIN BASELINE.'}}
export function validStory(value:unknown):value is StoryState{if(!value||typeof value!=='object')return false;const st=value as StoryState;const strings=(v:unknown)=>Array.isArray(v)&&v.length<=100&&v.every(x=>typeof x==='string'&&x.length<=1000);return st.revision===1&&Number.isInteger(st.stage)&&st.stage>=0&&st.stage<=24&&!!st.choices&&Object.values(st.choices).every(x=>typeof x==='string')&&strings(st.flags)&&strings(st.evidence)&&st.evidence.every(id=>!!EVIDENCE[id])&&Number.isInteger(st.relay)&&st.relay>=0&&st.relay<=3&&!!st.side&&Object.values(st.side).every(n=>Number.isInteger(n)&&n>=0)&&Object.keys(CONTACTS).every(k=>{const b=st.relationships?.[k as Contact];return !!b&&[b.trust,b.respect,b.resentment].every(n=>Number.isFinite(n)&&n>=-100&&n<=100)&&strings(b.memories)})&&Array.isArray(st.log)&&st.log.length<=60&&st.log.every(l=>typeof l.title==='string'&&typeof l.text==='string')}
export const CHAPTER_TWO=[
 {title:'The truck that never came',place:'deli',objective:'Ask Malik why the delivery never arrived.'},
 {title:'A visit from collections',place:'bishop',objective:'Find out what Bishop knows about the shipment.'},
 {title:'Two sides, one paymaster',place:'loading',objective:'Recover the shipment at the east loading bay.'},
 {title:'Who eats tonight?',place:'food',objective:'Bring the recovered supplies to Rosa.'},
 {title:'An honest recording',place:'garage',objective:'Ask Ruiz to trace the shipment’s dispatch recording.'},
 {title:'The tenant meeting',place:'meeting',objective:'Bring your findings to the courtyard noticeboard.'}
];
export const CHAPTER_THREE=[
 {title:'The public hearing',place:'meeting',objective:'Attend Director Vale’s Saint Mercer Initiative hearing.'},
 {title:'A better neighborhood',place:'clothes',objective:'Find out why Nia’s storefront permit was denied.'},
 {title:'An appointment with Vale',place:'meeting',objective:'Meet Director Vale after the hearing.'},
 {title:'Paper citizens',place:'bank',objective:'Compare the Initiative’s licensing records.'},
 {title:'The price of a permit',place:'clothes',objective:'Decide what Nia’s permit is worth.'}
];
export const CHAPTER_FOUR=[
 {title:'The photograph that forgot',place:'laundry',objective:'June remembers a neighbor the record no longer does.'},
 {title:'Two versions of Tuesday',place:'garage',objective:'Prove Theo existed before the cleanup crew finishes.'},
 {title:'The things they left',place:'meeting',objective:'Find what Theo’s erasure left behind in the neighborhood.'},
 {title:'Keep someone real',place:'meeting',objective:'Decide how the neighborhood holds a person the archive denies.'},
 {title:'No more blank pages',place:'meeting',objective:'Decide what happens to Theo’s name.'}
];
export const STORY_MOVES=[...CHAPTER_ONE,...CHAPTER_TWO,...CHAPTER_THREE,...CHAPTER_FOUR];
EVIDENCE.dispatch={title:'Matching dispatch accounts',text:'The seized shipment and the crew paid to recover it were both funded through Civic Renewal account 0317. The dispatcher ordered a controlled shortage.'};
EVIDENCE.recording={title:'An unedited dispatch recording',text:'Ruiz’s repaired recorder preserves a voice ordering the truck diversion. It names the Saint Mercer Initiative, and schedules a hearing chaired by Director Vale.'};
